if(select IdMenu from C_Menu Where IdMenu =1285)is null
INSERT [dbo].[C_Menu] ([IdMenu], [NombreMenu], [Descripcion], [IdPadre], [Clave], [IdDerecho], [Utilizar], [Procedimiento], [TipoIcono], [OrigenDll], [Parametros], [Orden], [AplicaMatriz], [DependeAlmacen], [TipoMenusPermitidos], [NoThread], [Contabilidad], [Almacen], [Basica], [Completa], [Obra]) VALUES (1285, N'Almacén', N'Almacén', 1166, N'', 1, 1, N'-', 0, N'Reporteador', N'', 6, 0, 0, N'', 0, 0, 0, 0, 1, 0)
if(select IdMenu from C_Menu Where IdMenu =1286)is null
INSERT [dbo].[C_Menu] ([IdMenu], [NombreMenu], [Descripcion], [IdPadre], [Clave], [IdDerecho], [Utilizar], [Procedimiento], [TipoIcono], [OrigenDll], [Parametros], [Orden], [AplicaMatriz], [DependeAlmacen], [TipoMenusPermitidos], [NoThread], [Contabilidad], [Almacen], [Basica], [Completa], [Obra]) VALUES (1286, N'Existencias en almacén', N'Existencias en almacén', 1285, N'', 1, 1, N'-', 1, N'Reporteador', N'', 1, 0, 0, N'', 0, 0, 0, 0, 1, 0)
if(select IdMenu from C_Menu Where IdMenu =1287)is null
INSERT [dbo].[C_Menu] ([IdMenu], [NombreMenu], [Descripcion], [IdPadre], [Clave], [IdDerecho], [Utilizar], [Procedimiento], [TipoIcono], [OrigenDll], [Parametros], [Orden], [AplicaMatriz], [DependeAlmacen], [TipoMenusPermitidos], [NoThread], [Contabilidad], [Almacen], [Basica], [Completa], [Obra]) VALUES (1287, N'Ingresos', N'Ingresos', 1166, N'', 1, 1, N'-', 0, N'Reporteador', N'', 7, 0, 0, N'', 0, 0, 0, 0, 1, 0)
if(select IdMenu from C_Menu Where IdMenu =1288)is null
INSERT [dbo].[C_Menu] ([IdMenu], [NombreMenu], [Descripcion], [IdPadre], [Clave], [IdDerecho], [Utilizar], [Procedimiento], [TipoIcono], [OrigenDll], [Parametros], [Orden], [AplicaMatriz], [DependeAlmacen], [TipoMenusPermitidos], [NoThread], [Contabilidad], [Almacen], [Basica], [Completa], [Obra]) VALUES (1288, N'Importación de Ingresos', N'Importación de Ingresos', 1287, N'', 1, 1, N'-', 1, N'Reporteador', N'', 1, 0, 0, N'', 0, 0, 0, 0, 1, 0)
if(select IdMenu from C_Menu Where IdMenu =1289)is null
INSERT [dbo].[C_Menu] ([IdMenu], [NombreMenu], [Descripcion], [IdPadre], [Clave], [IdDerecho], [Utilizar], [Procedimiento], [TipoIcono], [OrigenDll], [Parametros], [Orden], [AplicaMatriz], [DependeAlmacen], [TipoMenusPermitidos], [NoThread], [Contabilidad], [Almacen], [Basica], [Completa], [Obra]) VALUES (1289, N'Clasificacón Administrativa - Gobierno', N'Clasificacón Administrativa - Gobierno', 1126, N'', 1, 1, N'-', 1, N'Reporteador', N'', 18, 0, 0, N'', 0, 0, 0, 0, 1, 0)
if(select IdMenu from C_Menu Where IdMenu =1290)is null
INSERT [dbo].[C_Menu] ([IdMenu], [NombreMenu], [Descripcion], [IdPadre], [Clave], [IdDerecho], [Utilizar], [Procedimiento], [TipoIcono], [OrigenDll], [Parametros], [Orden], [AplicaMatriz], [DependeAlmacen], [TipoMenusPermitidos], [NoThread], [Contabilidad], [Almacen], [Basica], [Completa], [Obra]) VALUES (1290, N'Clasificacón Administrativa - Sector Paraestatal', N'Clasificacón Administrativa - Sector Paraestatal', 1126, N'', 1, 1, N'-', 1, N'Reporteador', N'', 19, 0, 0, N'', 0, 0, 0, 0, 1, 0)
if(select IdMenu from C_Menu Where IdMenu =1291)is null begin
INSERT [dbo].[C_Menu] ([IdMenu], [NombreMenu], [Descripcion], [IdPadre], [Clave], [IdDerecho], [Utilizar], [Procedimiento], [TipoIcono], [OrigenDll], [Parametros], [Orden], [AplicaMatriz], [DependeAlmacen], [TipoMenusPermitidos], [NoThread], [Contabilidad], [Almacen], [Basica], [Completa], [Obra]) VALUES (1291, N'Informe Sobre Pasivos Contingentes', N'Informe Sobre Pasivos Contingentes', 1074, N'', 1, 1, N'-', 1, N'Reporteador', N'', 8, 0, 0, N'', 0, 0, 0, 0, 1, 0)
exec SP_FirmasReporte'Informe Sobre Pasivos Contingentes'
end
if(select IdMenu from C_Menu Where IdMenu =1292)is null begin
INSERT [dbo].[C_Menu] ([IdMenu], [NombreMenu], [Descripcion], [IdPadre], [Clave], [IdDerecho], [Utilizar], [Procedimiento], [TipoIcono], [OrigenDll], [Parametros], [Orden], [AplicaMatriz], [DependeAlmacen], [TipoMenusPermitidos], [NoThread], [Contabilidad], [Almacen], [Basica], [Completa], [Obra]) VALUES (1292, N'Conciliación Presupuestal y Contable',N'Conciliación Presupuestal y Contable', 1081, N'', 1, 1, N'-', 0, N'Reporteador', N'', 6, 0, 0, N'', 0, 0, 0, 0, 1, 0)
end
if(select IdMenu from C_Menu Where IdMenu =1293)is null begin
INSERT [dbo].[C_Menu] ([IdMenu], [NombreMenu], [Descripcion], [IdPadre], [Clave], [IdDerecho], [Utilizar], [Procedimiento], [TipoIcono], [OrigenDll], [Parametros], [Orden], [AplicaMatriz], [DependeAlmacen], [TipoMenusPermitidos], [NoThread], [Contabilidad], [Almacen], [Basica], [Completa], [Obra]) VALUES (1293, N'Conciliación Entre los Ingresos Presupuestales y Contables', N'Conciliación Entre los Ingresos Presupuestales y Contables',1292, N'', 1, 1, N'-', 1, N'Reporteador', N'', 1, 0, 0, N'', 0, 0, 0, 0, 1, 0)
end
if(select IdMenu from C_Menu Where IdMenu =1294)is null begin
INSERT [dbo].[C_Menu] ([IdMenu], [NombreMenu], [Descripcion], [IdPadre], [Clave], [IdDerecho], [Utilizar], [Procedimiento], [TipoIcono], [OrigenDll], [Parametros], [Orden], [AplicaMatriz], [DependeAlmacen], [TipoMenusPermitidos], [NoThread], [Contabilidad], [Almacen], [Basica], [Completa], [Obra]) VALUES (1294, N'Conciliación Entre los Egresos Presupuestales y Gastos Contables',N'Conciliación Entre los Egresos Presupuestales y Gastos Contables', 1292, N'', 1, 1, N'-', 1, N'Reporteador', N'', 2, 0, 0, N'', 0, 0, 0, 0, 1, 0)
end
Update C_Menu SET NombreMenu = N'Notas de Desglose', Descripcion=N'Notas de Desglose' Where IdMenu=1081