UPDATE C_Contable SET NombreCuenta=UPPER(NombreCuenta),Descripcion='Importe  que  refleja  el reconocimiento de la baja de los bienes por pérdida, obsolescencia, deterioro, extravío, robo o siniestro, entre otros.' 
WHERE NumeroCuenta='55180-00000'
UPDATE C_Contable SET Descripcion='Representa el valor actualizado de los activos, pasivos y patrimonio del ente público que han sido reconocidos  contablemente  y  que  se  derivan  del  cambio  de  valores  por  encontrarse  en  un  entorno inflacionario' 
WHERE NumeroCuenta = '31300-00000'
UPDATE C_Contable SET Descripcion='Representa el importe de la actualización acumulada de los activos.' 
WHERE NumeroCuenta = '32300-00000'
UPDATE C_Contable SET Descripcion='Representa el importe de la actualización acumulada de los bienes inmuebles.' 
WHERE NumeroCuenta = '32310-00000'
UPDATE C_Contable SET Descripcion='Representa el importe de la actualización acumulada de los bienes muebles.' 
WHERE NumeroCuenta = '32320-00000'
UPDATE C_Contable SET Descripcion='Representa el importe de la actualización acumulada de los bienes intangibles.' 
WHERE NumeroCuenta = '32330-00000'
UPDATE C_Contable SET Descripcion='Representa el importe de la actualización acumulada de los otros activos.' 
WHERE NumeroCuenta = '32390-00000'
UPDATE C_Contable SET Descripcion='Representa  el  importe  correspondiente  a  la  corrección  de  las  omisiones,  inexactitudes  e imprecisiones de registros en los estados financieros de los entes públicos, o bien por los registros contables extemporáneos, por correcciones  por errores aritméticos, por errores en la aplicación de políticas contables, así como la inadvertencia o mala interpretación de hechos.' 
WHERE NumeroCuenta = '32520-00000'