DECLARE @Estructura1 INT
DECLARE @Estructura2 INT
SET @Estructura1= Convert(INT,SUBSTRING((SELECT TOP(1) VALOR FROM T_PARAMETROSCONTABLES WHERE NOMBREPARAMETRO = 'ESTRUCTURA CONTABLE'),1,1))
SET @Estructura2= Convert (INT,SUBSTRING((SELECT TOP(1) VALOR FROM T_PARAMETROSCONTABLES WHERE NOMBREPARAMETRO = 'ESTRUCTURA CONTABLE'),3,1))
DECLARE @CerosEstructura VARCHAR(20)
SET @CerosEstructura = REPLICATE('0',@Estructura2)

IF (SELECT UPPER(NombreCuenta) FROM C_Contable WHERE NumeroCuenta ='75'+REPLICATE('0',@Estructura1-2)+'-'+@CerosEstructura )<> 'CONTRATOS PARA INVERSIÓN MEDIANTE PROYECTOS PARA PRESTACIÓN DE SERVICIOS (PPS) Y SIMILARES'
BEGIN
UPDATE C_Contable SET NombreCuenta = 'CONTRATOS PARA INVERSIÓN MEDIANTE PROYECTOS PARA PRESTACIÓN DE SERVICIOS (PPS) Y SIMILARES' WHERE NumeroCuenta ='75'+REPLICATE('0',@Estructura1-2)+'-'+@CerosEstructura 
END

IF (SELECT UPPER(NombreCuenta) FROM C_Contable WHERE NumeroCuenta ='76'+REPLICATE('0',@Estructura1-2)+'-'+@CerosEstructura )<> 'BIENES EN CONCESIONADOS O EN COMODATO'
BEGIN
UPDATE C_Contable SET NombreCuenta = 'BIENES EN CONCESIONADOS O EN COMODATO' where NumeroCuenta ='76'+REPLICATE('0',@Estructura1-2)+'-'+@CerosEstructura 
END