--Crea un indice Unique en la tabla T_SellosPresupuestales
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
DROP INDEX Ak_Sello ON dbo.T_SellosPresupuestales
GO
CREATE UNIQUE NONCLUSTERED INDEX Ak_Sello ON dbo.T_SellosPresupuestales
	(
	Sello
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.T_SellosPresupuestales SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

-----------------------------------------

--Crea Unique de sello y lyear
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.T_SellosPresupuestales ADD CONSTRAINT
	Fk_Sello_LYear UNIQUE NONCLUSTERED 
	(
	Sello,
	LYear
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.T_SellosPresupuestales SET (LOCK_ESCALATION = TABLE)
GO
COMMIT