--Crea inidice nuevo y modifica indice existente
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
DROP INDEX AK_Fecha_Tipo_Cuenta ON dbo.D_Ingresos
GO
CREATE NONCLUSTERED INDEX AK_Fecha_Tipo_Cuenta ON dbo.D_Ingresos
	(
	Fecha,
	Tipo,
	IdcuentaBancaria,
	IdCaja,
	IdCliente
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX Ak_IdCliente ON dbo.D_Ingresos
	(
	Fecha,
	Tipo,
	IdCliente
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE dbo.D_Ingresos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
