-- Aplicación de las reformas de CONAC del 27-09-2018 a la BD de K2
UPDATE C_ClasificacionGasto SET CLAVE='00000' WHERE IdClasificacionGI=4346;
UPDATE C_ClasificacionGasto SET CLAVE='01000' WHERE IdClasificacionGI=4347;
UPDATE C_ClasificacionGasto SET CLAVE='02000' WHERE IdClasificacionGI=4348;
UPDATE C_ClasificacionGasto SET CLAVE=NULL WHERE IdClasificacionGI=4100;
UPDATE C_ClasificacionGasto SET Armonizado=0 WHERE IdClasificacionGI IN (140, 160, 4100);

UPDATE C_ClasificacionGasto SET Descripcion='Ingresos derivados de financiamientos', Definicion='Son los ingresos obtenidos por la celebración de empréstitos internos o externos, a corto o largo plazo, aprobados en términos de la legislación correspondiente. Los créditos que se obtienen son por: emisiones de instrumentos en mercados nacionales e internacionales de capital, organismos financieros internacionales, créditos bilaterales y otras fuentes ' WHERE IdClasificacionGI=4346;
UPDATE C_ClasificacionGasto SET Descripcion='Endeudamiento interno', Definicion='Financiamiento derivado del resultado positivo neto de los recursos que provienen de obligaciones contraídas por los entes públicos y empresas productivas del estado del ámbito federal, considerando lo previsto en la legislación aplicable en la materia, con acreedores nacionales y pagaderos en el interior del país en moneda nacional, incluye el diferimiento de pagos ' WHERE IdClasificacionGI=4347;
UPDATE C_ClasificacionGasto SET Descripcion='Endeudamiento externo', Definicion='Financiamiento derivado del resultado positivo neto de los recursos que provienen de obligaciones contraídas por los entes públicos y empresas productivas del estado del ámbito federal, considerando lo previsto en la legislación aplicable en la materia, con acreedores extranjeros y pagaderos en el exterior del país en moneda extranjera ' WHERE IdClasificacionGI=4348;
UPDATE C_ClasificacionGasto SET Descripcion='Impuestos', Definicion='Son las contribuciones establecidas en ley que deben pagar las personas físicas y morales que se encuentran en la situación jurídica o de hecho prevista por la misma y que sean distintas de las aportaciones de seguridad social, contribuciones de mejoras y derechos ' WHERE IdClasificacionGI=4312;
UPDATE C_ClasificacionGasto SET Descripcion='Impuestos sobre los ingresos', Definicion='Son las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan sobre los ingresos de las personas físicas y/o morales, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4313;
UPDATE C_ClasificacionGasto SET Descripcion='Impuestos sobre el patrimonio', Definicion='Son las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan sobre los bienes propiedad de las personas físicas y/o morales, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4314;
UPDATE C_ClasificacionGasto SET Descripcion='Impuestos sobre la producción, el consumo y las transacciones', Definicion='Son las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan sobre la actividad económica relacionada con la producción, el consumo y las transacciones que realizan las personas físicas y/o morales, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4315;
UPDATE C_ClasificacionGasto SET Descripcion='Impuestos al comercio exterior', Definicion='Son las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan sobre las actividades de importación y exportación que realizan las personas físicas y/o morales, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4316;
UPDATE C_ClasificacionGasto SET Descripcion='Impuestos sobre nóminas y asimilables', Definicion='Son las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan sobre la base gravable de las remuneraciones al trabajo personal subordinado o el que corresponda, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4317;
UPDATE C_ClasificacionGasto SET Descripcion='Impuestos ecológicos', Definicion='Son las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan a las personas físicas y/o morales, por la afectación preventiva o correctiva que se ocasione en flora, fauna, medio ambiente o todo aquello relacionado a la ecología, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4318;
UPDATE C_ClasificacionGasto SET Descripcion='Accesorios de impuestos', Definicion='Son los ingresos que se perciben por concepto de recargos, sanciones, gastos de ejecución, indemnizaciones, entre otros, asociados a los impuestos, cuando éstos no se cubran oportunamente, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4319;
UPDATE C_ClasificacionGasto SET Descripcion='Otros impuestos', Definicion='Son los ingresos que se perciben por conceptos no incluidos en los tipos anteriores, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4320;
UPDATE C_ClasificacionGasto SET Descripcion='Impuestos no comprendidos en la Ley de Ingresos vigente, causados en ejercicios fiscales anteriores pendientes de liquidación o pago', Definicion='Son los ingresos que se recaudan en el ejercicio corriente, por impuestos pendientes de liquidación o pago causados en ejercicios fiscales anteriores, no incluidos en la Ley de Ingresos vigente ' WHERE IdClasificacionGI=4321;
UPDATE C_ClasificacionGasto SET Descripcion='Cuotas y aportaciones de seguridad social', Definicion='Son las contribuciones establecidas en ley a cargo de personas que son sustituidas por el Estado en el cumplimiento de obligaciones fijadas por la ley en materia de seguridad social o a las personas que se beneficien en forma especial por servicios de seguridad social proporcionados por el mismo Estado ' WHERE IdClasificacionGI=4322;
UPDATE C_ClasificacionGasto SET Descripcion='Aportaciones para fondos de vivienda', Definicion='Son los ingresos que reciben los entes públicos que prestan los servicios de seguridad social, para cubrir las obligaciones relativas a los fondos de vivienda, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4323;
UPDATE C_ClasificacionGasto SET Descripcion='Cuotas para la seguridad social', Definicion='Son los ingresos que reciben los entes públicos que prestan los servicios de seguridad social, para cubrir las obligaciones relativas a la previsión social, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4324;
UPDATE C_ClasificacionGasto SET Descripcion='Cuotas de ahorro para el retiro', Definicion='Son los ingresos que reciben los entes públicos que prestan los servicios de seguridad social, para cubrir las obligaciones relativas a fondos del ahorro para el retiro, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4325;
UPDATE C_ClasificacionGasto SET Descripcion='Otras cuotas y aportaciones para la seguridad social', Definicion='Son los ingresos que reciben los entes públicos que prestan los servicios de seguridad social, por conceptos no incluidos en los tipos anteriores, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4326;
UPDATE C_ClasificacionGasto SET Descripcion='Accesorios de cuotas y aportaciones de seguridad social', Definicion='Son los ingresos que se perciben por concepto de recargos, sanciones, gastos de ejecución, indemnizaciones, entre otros, asociados a las cuotas y aportaciones de seguridad social, cuando éstas no se cubran oportunamente de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4327;
UPDATE C_ClasificacionGasto SET Descripcion='Contribuciones de mejoras', Definicion='Son las establecidas en Ley a cargo de las personas físicas y morales que se beneficien de manera directa por obras públicas ' WHERE IdClasificacionGI=4328;
UPDATE C_ClasificacionGasto SET Descripcion='Contribución de mejoras por obras públicas', Definicion='Son las contribuciones derivadas de los beneficios diferenciales particulares por la realización de obras públicas, a cargo de las personas físicas y/o morales, independientemente de la utilidad general colectiva, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4329;
UPDATE C_ClasificacionGasto SET Descripcion='Contribuciones de mejoras no comprendidas en las fracciones de la Ley de Ingresos vigente, causadas en ejercicios fiscales anteriores pendientes de liquidación o pago', Definicion='Son los ingresos que se recaudan en el ejercicio corriente, por contribuciones de mejoras pendientes de liquidación o pago causadas en ejercicios fiscales anteriores, no incluidas en la Ley de Ingresos vigente ' WHERE IdClasificacionGI=4330;
UPDATE C_ClasificacionGasto SET Descripcion='Derechos', Definicion='Son las contribuciones establecidas en Ley por el uso o aprovechamiento de los bienes del dominio público, así como por recibir servicios que presta el Estado en sus funciones de derecho público, excepto cuando se presten por organismos descentralizados u órganos desconcentrados cuando en este último caso, se trate de contraprestaciones que no se encuentren previstas en las leyes correspondientes. También son derechos las contribuciones a cargo de los organismos públicos descentralizados por prestar servicios exclusivos del Estado ' WHERE IdClasificacionGI=4140;
UPDATE C_ClasificacionGasto SET Descripcion='Derechos por el uso, goce, aprovechamiento o explotación de bienes de dominio público', Definicion='Son las contribuciones derivadas de la contraprestación del uso, goce, aprovechamiento o explotación de bienes de dominio público, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4331;
UPDATE C_ClasificacionGasto SET Descripcion='Derechos a los hidrocarburos (Derogado)', Definicion=' ' WHERE IdClasificacionGI=4332;
UPDATE C_ClasificacionGasto SET Descripcion='Derechos por prestación de servicios', Definicion='Son las contribuciones derivadas por la contraprestación de servicios exclusivos del Estado, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4143;
UPDATE C_ClasificacionGasto SET Descripcion='Otros Derechos', Definicion='Son las contribuciones derivadas por contraprestaciones no incluidas en los tipos anteriores, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4333;
UPDATE C_ClasificacionGasto SET Descripcion='Accesorios de Derechos', Definicion='Son los ingresos que se perciben por concepto de recargos, sanciones, gastos de ejecución,   indemnizaciones, entre otros, asociados a los derechos, cuando éstos no se cubran oportunamente, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4334;
UPDATE C_ClasificacionGasto SET Descripcion='Derechos no comprendidos en la Ley de Ingresos vigente causados en ejercicios fiscales anteriores pendientes de liquidación o pago', Definicion='Son las contribuciones que se recaudan en el ejercicio corriente, por derechos pendientes de liquidación o pago causados en ejercicios fiscales anteriores, no incluidos en la Ley de Ingresos vigente ' WHERE IdClasificacionGI=4335;
UPDATE C_ClasificacionGasto SET Descripcion='Productos', Definicion='Son los ingresos por contraprestaciones por los servicios que preste el Estado en sus funciones de derecho privado ' WHERE IdClasificacionGI=4150;
UPDATE C_ClasificacionGasto SET Descripcion='Productos', Definicion='Son los ingresos por concepto de servicios otorgados por funciones de derecho privado, tales como los intereses que generan las cuentas bancarias de los entes públicos, entre otros, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4336;
UPDATE C_ClasificacionGasto SET Descripcion='Productos de capital (Derogado)', Definicion=' ' WHERE IdClasificacionGI=4337;
UPDATE C_ClasificacionGasto SET Descripcion='Productos no comprendidos en la Ley de Ingresos vigente causados en ejercicios fiscales anteriores pendientes de liquidación o pago', Definicion='Son los ingresos que se recaudan en el ejercicio corriente, por productos pendientes de liquidación o pago causados en ejercicios fiscales anteriores, no incluidos en la Ley de Ingresos vigente ' WHERE IdClasificacionGI=4159;
UPDATE C_ClasificacionGasto SET Descripcion='Aprovechamientos', Definicion='Son los ingresos que percibe el Estado por funciones de derecho público distintos de: las contribuciones, los ingresos derivados de financiamientos y de los que obtengan los organismos descentralizados y las empresas de participación estatal y municipal ' WHERE IdClasificacionGI=4160;
UPDATE C_ClasificacionGasto SET Descripcion='Aprovechamientos', Definicion='Son los ingresos que se perciben por funciones de derecho público, cuyos elementos pueden no estar previstos en una Ley sino, en una disposición administrativa de carácter general, provenientes de multas e indemnizaciones no fiscales, reintegros, juegos y sorteos, donativos, entre otros ' WHERE IdClasificacionGI=4161;
UPDATE C_ClasificacionGasto SET Descripcion='Aprovechamientos patrimoniales', Definicion='Son los ingresos que se perciben por uso o enajenación de bienes muebles, inmuebles e intangibles, por recuperaciones de capital o en su caso patrimonio invertido, de conformidad con la legislación aplicable en la materia ' WHERE IdClasificacionGI=4162;
UPDATE C_ClasificacionGasto SET Descripcion='Aprovechamientos no comprendidos en la Ley de Ingresos vigente causados en ejercicios fiscales anteriores pendientes de liquidación o pago', Definicion='Son los ingresos que se recaudan en el ejercicio corriente, por aprovechamientos pendientes de liquidación o pago causados en ejercicios fiscales anteriores, no incluidos en la Ley de Ingresos vigente ' WHERE IdClasificacionGI=4169;
UPDATE C_ClasificacionGasto SET Descripcion='Ingresos por venta de bienes, prestación de servicios y otros ingresos', Definicion='Son los ingresos propios obtenidos por las Instituciones Públicas de Seguridad Social, las Empresas Productivas del Estado, las entidades de la administración pública paraestatal y paramunicipal, los poderes legislativo y judicial, y los órganos autónomos federales y estatales, por sus actividades de producción, comercialización o prestación de servicios; así como otros ingresos por sus actividades diversas no inherentes a su operación, que generen recursos ' WHERE IdClasificacionGI=4170;
UPDATE C_ClasificacionGasto SET Descripcion='Ingresos por venta de bienes y prestación de servicios de instituciones públicas de seguridad social', Definicion='Son los ingresos propios obtenidos por las Instituciones Públicas de Seguridad Social por sus actividades de producción, comercialización o prestación de servicios ' WHERE IdClasificacionGI=4171;
UPDATE C_ClasificacionGasto SET Descripcion='Ingresos por venta de bienes y prestación de servicios de empresas productivas del estado', Definicion='Son los ingresos propios obtenidos por las Empresas Productivas del Estado por sus actividades de producción, comercialización o prestación de servicios ' WHERE IdClasificacionGI=4172;
UPDATE C_ClasificacionGasto SET Descripcion='Ingresos por venta de bienes y prestación de servicios de entidades paraestatales y fideicomisos no empresariales y no financieros', Definicion='Son los ingresos propios obtenidos por las Entidades Paraestatales y Fideicomisos No Empresariales y No Financieros por sus actividades de producción, comercialización o prestación de servicios ' WHERE IdClasificacionGI=4173;
UPDATE C_ClasificacionGasto SET Descripcion='Participaciones, aportaciones, convenios, incentivos derivados de la colaboración fiscal y fondos distintos de aportaciones', Definicion='Son los recursos que reciben las Entidades Federativas y los Municipios por concepto de participaciones, aportaciones, convenios, incentivos derivados de la colaboración fiscal y fondos distintos de aportaciones ' WHERE IdClasificacionGI=4338;
UPDATE C_ClasificacionGasto SET Descripcion='Participaciones', Definicion='Son los ingresos que reciben las Entidades Federativas y Municipios que se derivan de la adhesión al Sistema Nacional de Coordinación Fiscal, así como las que correspondan a sistemas estatales de coordinación fiscal, determinados por las leyes correspondientes ' WHERE IdClasificacionGI=4339;
UPDATE C_ClasificacionGasto SET Descripcion='Aportaciones ', Definicion='Son los ingresos que reciben las Entidades Federativas y Municipios previstos en la Ley de Coordinación Fiscal, cuyo gasto está condicionado a la consecución y cumplimiento de los objetivos que para cada tipo de aportación establece la legislación aplicable en la materia ' WHERE IdClasificacionGI=4340;
UPDATE C_ClasificacionGasto SET Descripcion='Convenios', Definicion='Son los ingresos que reciben las Entidades Federativas y Municipios derivados de convenios de coordinación, colaboración, reasignación o descentralización según corresponda, los cuales se acuerdan entre la Federación, las Entidades Federativas y/o los Municipios ' WHERE IdClasificacionGI=4341;
UPDATE C_ClasificacionGasto SET Descripcion='Transferencias, asignaciones, subsidios y subvenciones, y pensiones y jubilaciones', Definicion='Son los recursos que reciben en forma directa o indirecta los entes públicos como parte de su política económica y social, de acuerdo a las estrategias y prioridades de desarrollo para el sostenimiento y desempeño de sus actividades ' WHERE IdClasificacionGI=4190;
UPDATE C_ClasificacionGasto SET Descripcion='Transferencias y asignaciones', Definicion='Son los ingresos que reciben los entes públicos con el objeto de sufragar gastos inherentes a sus atribuciones ' WHERE IdClasificacionGI=4191;
UPDATE C_ClasificacionGasto SET Descripcion='Transferencias al resto del sector público (Derogado)', Definicion=' ' WHERE IdClasificacionGI=4192;
UPDATE C_ClasificacionGasto SET Descripcion='Subsidios y subvenciones', Definicion='Son los ingresos destinados para el desarrollo de actividades prioritarias de interés general, que reciben los entes públicos mediante asignación directa de recursos, con el fin de favorecer a los diferentes sectores de la sociedad para: apoyar en sus operaciones, mantener los niveles en los precios, apoyar el consumo, la distribución y comercialización de bienes, motivar la inversión, cubrir impactos financieros, promover la innovación tecnológica, y para el fomento de las actividades agropecuarias, industriales o de servicios ' WHERE IdClasificacionGI=4342;
UPDATE C_ClasificacionGasto SET Descripcion='Ayudas sociales (Derogado)', Definicion=' ' WHERE IdClasificacionGI=4343;
UPDATE C_ClasificacionGasto SET Descripcion='Pensiones y jubilaciones ', Definicion='Son los ingresos que reciben los entes públicos de seguridad social, que cubre el Gobierno Federal, Estatal o Municipal según corresponda, por el pago de pensiones y jubilaciones ' WHERE IdClasificacionGI=4344;
UPDATE C_ClasificacionGasto SET Descripcion='Transferencias a fideicomisos, mandatos y análogos (Derogado)', Definicion=' ' WHERE IdClasificacionGI=4345;

DELETE FROM C_ClasificacionGasto WHERE CLAVE IN ('03000','63000','74000','75000','76000','77000','78000','79000','84000','85000','97000');
DECLARE @CRIconsec INT = (SELECT MAX (IdClasificacionGI) FROM C_ClasificacionGasto) 
INSERT INTO [dbo].[C_ClasificacionGasto]
           ([IdClasificacionGI],[TipoIngreso],[Descripcion],[Definicion],[Importe],[Nivel],[Clave],[IdClasificacionGIPadre],[Armonizado],[IdCuentaContable],[ClaveContable],[Protegido],[Utilizar])
     VALUES
 (@CRIconsec+1,'I','Financiamiento interno','Son los recursos que provienen de obligaciones contraídas por las Entidades Federativas, los Municipios y en su caso, las entidades del sector paraestatal o paramunicipal, a corto o largo plazo, con acreedores nacionales y pagaderos en el interior del país en moneda nacional, considerando lo previsto en la legislación aplicable en la materia',0.00,3,'03000',4346,1,NULL,NULL,NULL,NULL)
,(@CRIconsec+2,'I','Accesorios de aprovechamientos','Son los ingresos que se perciben por concepto de recargos, sanciones, gastos de ejecución e  indemnizaciones, entre otros, asociados a los aprovechamientos, cuando éstos no se cubran oportunamente de conformidad con la legislación aplicable en la materia',0.00,3,'63000',4160,1,NULL,NULL,NULL,NULL)
,(@CRIconsec+3,'I','Ingresos por venta de bienes y prestación de servicios de entidades paraestatales empresariales no financieras con participación estatal mayoritaria','Son los ingresos propios obtenidos por las Entidades Paraestatales Empresariales No Financieras con Participación Estatal Mayoritaria por sus actividades de producción, comercialización o prestación de servicios',0.00,3,'74000',4170,1,NULL,NULL,NULL,NULL)
,(@CRIconsec+4,'I','Ingresos por venta de bienes y prestación de servicios de entidades paraestatales empresariales financieras monetarias con participación estatal mayoritaria','Son los ingresos propios obtenidos por las Entidades Paraestatales Empresariales Financieras Monetarias con Participación Estatal Mayoritaria por sus actividades de producción, comercialización o prestación de servicios',0.00,3,'75000',4170,1,NULL,NULL,NULL,NULL)
,(@CRIconsec+5,'I','Ingresos por venta de bienes y prestación de servicios de entidades paraestatales empresariales financieras no monetarias con participación estatal mayoritaria','Son los ingresos propios obtenidos por las Entidades Paraestatales Empresariales Financieras No Monetarias con Participación Estatal Mayoritaria por sus actividades de producción, comercialización o prestación de servicios',0.00,3,'76000',4170,1,NULL,NULL,NULL,NULL)
,(@CRIconsec+6,'I','Ingresos por venta de bienes y prestación de servicios de fideicomisos financieros públicos con participación estatal mayoritaria','Son los ingresos propios obtenidos por los Fideicomisos Financieros Públicos con Participación Estatal Mayoritaria por sus actividades de producción, comercialización o prestación de servicios',0.00,3,'77000',4170,1,NULL,NULL,NULL,NULL)
,(@CRIconsec+7,'I','Ingresos por venta de bienes y prestación de servicios de los Poderes Legislativo y Judicial, y de los Órganos Autónomos','Son los ingresos propios obtenidos por los Poderes Legislativo y Judicial, y los Órganos Autónomos por sus actividades de producción, comercialización o prestación de servicios',0.00,3,'78000',4170,1,NULL,NULL,NULL,NULL)
,(@CRIconsec+8,'I','Otros ingresos','Son los ingresos propios obtenidos por los Poderes Legislativo y Judicial, los Órganos Autónomos y las entidades de la administración pública paraestatal y paramunicipal por sus actividades diversas no inherentes a su operación que generan recursos y que no sean ingresos por venta de bienes o prestación de servicios, tales como donativos, entre otros',0.00,3,'79000',4170,1,NULL,NULL,NULL,NULL)
,(@CRIconsec+9,'I','Incentivos derivados de la colaboración fiscal','Son los ingresos que reciben las Entidades Federativas y Municipios derivados del ejercicio de facultades delegadas por la Federación mediante la celebración de convenios de colaboración administrativa en materia fiscal; que comprenden las funciones de recaudación, fiscalización y administración de ingresos federales y por las que a cambio reciben incentivos económicos que implican la retribución de su colaboración',0.00,3,'84000',4338,1,NULL,NULL,NULL,NULL)
,(@CRIconsec+10,'I','Fondos distintos de aportaciones','Son los ingresos que reciben las Entidades Federativas y Municipios derivados de fondos distintos de aportaciones y previstos en disposiciones específicas, tales como: Fondo para Entidades Federativas y Municipios Productores de Hidrocarburos, y Fondo para el Desarrollo Regional Sustentable de Estados y Municipios Mineros (Fondo Minero), entre otros',0.00,3,'85000',4338,1,NULL,NULL,NULL,NULL)
,(@CRIconsec+11,'I','Transferencias del Fondo Mexicano del Petróleo para la Estabilización y el Desarrollo','Son los ingresos que reciben los entes públicos por transferencias del Fondo Mexicano del Petróleo para la Estabilización y el Desarrollo',0.00,3,'97000',4190,1,NULL,NULL,NULL,NULL)
;





