'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DSetArturo"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DSetArturo
    Inherits Global.System.Data.DataSet
    
    Private tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF")) Is Nothing) Then
                MyBase.Tables.Add(New SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable(ds.Tables("SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF() As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable
        Get
            Return Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DSetArturo = CType(MyBase.Clone,DSetArturo)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF")) Is Nothing) Then
                MyBase.Tables.Add(New SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable(ds.Tables("SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF = CType(MyBase.Tables("SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF"),SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable)
        If (initTable = true) Then
            If (Not (Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF) Is Nothing) Then
                Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "DSetArturo"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DSetArturo.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF = New SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable()
        MyBase.Tables.Add(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializeSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DSetArturo = New DSetArturo()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEventHandler(ByVal sender As Object, ByVal e As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnNombreCuenta As Global.System.Data.DataColumn
        
        Private columnSaldo As Global.System.Data.DataColumn
        
        Private columnDisposiciones As Global.System.Data.DataColumn
        
        Private columnAmortizaciones As Global.System.Data.DataColumn
        
        Private columnRevaluaciones As Global.System.Data.DataColumn
        
        Private columnSaldoFinal As Global.System.Data.DataColumn
        
        Private columnPagoDeIntereses As Global.System.Data.DataColumn
        
        Private columnPagoDeComisiones As Global.System.Data.DataColumn
        
        Private columnmes As Global.System.Data.DataColumn
        
        Private columnyear As Global.System.Data.DataColumn
        
        Private columnDeudaPublica As Global.System.Data.DataColumn
        
        Private columnPlazo As Global.System.Data.DataColumn
        
        Private columnordenamiento As Global.System.Data.DataColumn
        
        Private columnordenamiento2 As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property NombreCuentaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnNombreCuenta
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SaldoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSaldo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DisposicionesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDisposiciones
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property AmortizacionesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAmortizaciones
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property RevaluacionesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRevaluaciones
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property SaldoFinalColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSaldoFinal
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PagoDeInteresesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPagoDeIntereses
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PagoDeComisionesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPagoDeComisiones
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property mesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnmes
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property yearColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnyear
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DeudaPublicaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDeudaPublica
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PlazoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPlazo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ordenamientoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnordenamiento
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property ordenamiento2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnordenamiento2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow
            Get
                Return CType(Me.Rows(index),SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChanging As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChanged As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowDeleting As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowDeleted As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub AddSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow(ByVal row As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function AddSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow(ByVal NombreCuenta As String, ByVal Saldo As String, ByVal Disposiciones As String, ByVal Amortizaciones As String, ByVal Revaluaciones As String, ByVal SaldoFinal As String, ByVal PagoDeIntereses As String, ByVal PagoDeComisiones As String, ByVal mes As String, ByVal year As String, ByVal DeudaPublica As String, ByVal Plazo As String, ByVal ordenamiento As String, ByVal ordenamiento2 As String) As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow
            Dim rowSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow = CType(Me.NewRow,SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow)
            Dim columnValuesArray() As Object = New Object() {NombreCuenta, Saldo, Disposiciones, Amortizaciones, Revaluaciones, SaldoFinal, PagoDeIntereses, PagoDeComisiones, mes, year, DeudaPublica, Plazo, ordenamiento, ordenamiento2}
            rowSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow)
            Return rowSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable = CType(MyBase.Clone,SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnNombreCuenta = MyBase.Columns("NombreCuenta")
            Me.columnSaldo = MyBase.Columns("Saldo")
            Me.columnDisposiciones = MyBase.Columns("Disposiciones")
            Me.columnAmortizaciones = MyBase.Columns("Amortizaciones")
            Me.columnRevaluaciones = MyBase.Columns("Revaluaciones")
            Me.columnSaldoFinal = MyBase.Columns("SaldoFinal")
            Me.columnPagoDeIntereses = MyBase.Columns("PagoDeIntereses")
            Me.columnPagoDeComisiones = MyBase.Columns("PagoDeComisiones")
            Me.columnmes = MyBase.Columns("mes")
            Me.columnyear = MyBase.Columns("year")
            Me.columnDeudaPublica = MyBase.Columns("DeudaPublica")
            Me.columnPlazo = MyBase.Columns("Plazo")
            Me.columnordenamiento = MyBase.Columns("ordenamiento")
            Me.columnordenamiento2 = MyBase.Columns("ordenamiento2")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnNombreCuenta = New Global.System.Data.DataColumn("NombreCuenta", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnNombreCuenta)
            Me.columnSaldo = New Global.System.Data.DataColumn("Saldo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSaldo)
            Me.columnDisposiciones = New Global.System.Data.DataColumn("Disposiciones", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDisposiciones)
            Me.columnAmortizaciones = New Global.System.Data.DataColumn("Amortizaciones", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAmortizaciones)
            Me.columnRevaluaciones = New Global.System.Data.DataColumn("Revaluaciones", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRevaluaciones)
            Me.columnSaldoFinal = New Global.System.Data.DataColumn("SaldoFinal", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSaldoFinal)
            Me.columnPagoDeIntereses = New Global.System.Data.DataColumn("PagoDeIntereses", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPagoDeIntereses)
            Me.columnPagoDeComisiones = New Global.System.Data.DataColumn("PagoDeComisiones", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPagoDeComisiones)
            Me.columnmes = New Global.System.Data.DataColumn("mes", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnmes)
            Me.columnyear = New Global.System.Data.DataColumn("year", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnyear)
            Me.columnDeudaPublica = New Global.System.Data.DataColumn("DeudaPublica", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDeudaPublica)
            Me.columnPlazo = New Global.System.Data.DataColumn("Plazo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPlazo)
            Me.columnordenamiento = New Global.System.Data.DataColumn("ordenamiento", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnordenamiento)
            Me.columnordenamiento2 = New Global.System.Data.DataColumn("ordenamiento2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnordenamiento2)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function NewSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow() As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow
            Return CType(Me.NewRow,SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangedEvent) Is Nothing) Then
                RaiseEvent SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChanged(Me, New SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEvent(CType(e.Row,SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangingEvent) Is Nothing) Then
                RaiseEvent SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChanging(Me, New SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEvent(CType(e.Row,SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowDeletedEvent) Is Nothing) Then
                RaiseEvent SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowDeleted(Me, New SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEvent(CType(e.Row,SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowDeletingEvent) Is Nothing) Then
                RaiseEvent SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowDeleting(Me, New SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEvent(CType(e.Row,SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub RemoveSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow(ByVal row As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As DSetArturo = New DSetArturo()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow
        Inherits Global.System.Data.DataRow
        
        Private tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF = CType(Me.Table,SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property NombreCuenta() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.NombreCuentaColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'NombreCuenta' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPubli"& _ 
                            "caPorPeriodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.NombreCuentaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property Saldo() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.SaldoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'Saldo' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPublicaPorPe"& _ 
                            "riodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.SaldoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property Disposiciones() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.DisposicionesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'Disposiciones' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPubl"& _ 
                            "icaPorPeriodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.DisposicionesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property Amortizaciones() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.AmortizacionesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'Amortizaciones' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPub"& _ 
                            "licaPorPeriodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.AmortizacionesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property Revaluaciones() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.RevaluacionesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'Revaluaciones' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPubl"& _ 
                            "icaPorPeriodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.RevaluacionesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property SaldoFinal() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.SaldoFinalColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'SaldoFinal' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPublica"& _ 
                            "PorPeriodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.SaldoFinalColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PagoDeIntereses() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PagoDeInteresesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'PagoDeIntereses' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPu"& _ 
                            "blicaPorPeriodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PagoDeInteresesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PagoDeComisiones() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PagoDeComisionesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'PagoDeComisiones' de la tabla 'SP_RPT_AnaliticoDeLaDeudaP"& _ 
                            "ublicaPorPeriodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PagoDeComisionesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property mes() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.mesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'mes' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPublicaPorPeri"& _ 
                            "odoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.mesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property year() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.yearColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'year' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPublicaPorPer"& _ 
                            "iodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.yearColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DeudaPublica() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.DeudaPublicaColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'DeudaPublica' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPubli"& _ 
                            "caPorPeriodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.DeudaPublicaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property Plazo() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PlazoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'Plazo' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPublicaPorPe"& _ 
                            "riodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PlazoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ordenamiento() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.ordenamientoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'ordenamiento' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPubli"& _ 
                            "caPorPeriodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.ordenamientoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property ordenamiento2() As String
            Get
                Try 
                    Return CType(Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.ordenamiento2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'ordenamiento2' de la tabla 'SP_RPT_AnaliticoDeLaDeudaPubl"& _ 
                            "icaPorPeriodoLDF' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.ordenamiento2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsNombreCuentaNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.NombreCuentaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetNombreCuentaNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.NombreCuentaColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSaldoNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.SaldoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSaldoNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.SaldoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDisposicionesNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.DisposicionesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDisposicionesNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.DisposicionesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsAmortizacionesNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.AmortizacionesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetAmortizacionesNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.AmortizacionesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsRevaluacionesNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.RevaluacionesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetRevaluacionesNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.RevaluacionesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsSaldoFinalNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.SaldoFinalColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetSaldoFinalNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.SaldoFinalColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPagoDeInteresesNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PagoDeInteresesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPagoDeInteresesNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PagoDeInteresesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPagoDeComisionesNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PagoDeComisionesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPagoDeComisionesNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PagoDeComisionesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsmesNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.mesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetmesNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.mesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsyearNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.yearColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetyearNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.yearColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsDeudaPublicaNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.DeudaPublicaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetDeudaPublicaNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.DeudaPublicaColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsPlazoNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PlazoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetPlazoNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.PlazoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsordenamientoNull() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.ordenamientoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetordenamientoNull()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.ordenamientoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function Isordenamiento2Null() As Boolean
            Return Me.IsNull(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.ordenamiento2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub Setordenamiento2Null()
            Me(Me.tableSP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDF.ordenamiento2Column) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As SP_RPT_AnaliticoDeLaDeudaPublicaPorPeriodoLDFRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
