/****** Object:  StoredProcedure [dbo].[SP_ClasificacionEconomica]    Script Date: 03/21/2013 12:59:52 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SP_ClasificacionEconomica]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[SP_ClasificacionEconomica]
GO

/****** Object:  StoredProcedure [dbo].[SP_ClasificacionEconomica]    Script Date: 03/21/2013 12:59:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[SP_ClasificacionEconomica]

AS
DECLARE @Tabla AS Table(
	[Codigo] [varchar](50) NULL,
	[Concepto] [varchar](max) NULL,
	[Nota1] [varchar](max) NULL,
	[Negritas] [bit]NUll
) 
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1', N'INGRESOS', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1', N'INGRESOS CORRIENTES', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1', N'Impuestos', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.1', N'Impuestos sobre el ingreso, las utilidades y las ganancias de capital', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.1.1', N'De las personas Fisicas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.1.1.1', N'Impuestos sobre los ingresos ', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.1.2', N'De empresas y otras corporaciones (personas morales)', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.1.2.1', N'Impuestos sobre los ingresos ', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.1.3', N'No clasificables', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.2', N'Impuestos sobre la nómina y la fuerza de trabajo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.2.1', N'Impuesto sobre Nomina y Asimilables', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.3', N'Impuestos sobre la propiedad.', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.4', N'Impuestos sobre los bienes y servicios', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.4.1', N'Impuestos sobre la producción, el consumo y las transacciones', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.4.1.1', N'Impuesto al Valor Agregado', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.4.1.2', N'Impuesto Especial sobre Producción y Servicios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.4.1.3', N'Otros Impuestos sobre Bienes y Servicios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.5', N'Impuestos sobre el comercio y las transacciones internacionales/Comercio Exterior', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.5.1', N'Impuesto a la Importación', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.5.2', N'Impuesto a la Exportación', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.6', N'Impuestos Ecológicos', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.7', N'Impuestos a los rendimientos petroleros', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.8', N'Otros impuestos', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.1.8', N'Accesorios', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.2', N'Contribuciones a la Seguridad Social', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.2.1', N'Contribuciones de los Empleados', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.2.2', N'Contribuciones de los Empleadores', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.2.3', N'Contribuciones de los Trabajadores por cuenta propia o no empleados', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.2.4', N'Contribuciones no clasificables', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.3', N'Contribuciones de Mejoras                                 ', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.4', N'Derechos, Productos y Aprovechamientos Corrientes                                 ', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.4.1', N'Derechos no incluidos en otros conceptos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.4.2', N'Productos corrientes no incluidos en otros conceptos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.4.3', N'Aprovechamientos corrientes no incluidos en otros conceptos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.5', N'Rentas de la Propiedad', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.5.1', N'Intereses', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.5.1.1', N'Internos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.5.1.2', N'Externos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.5.2', N'Dividendos y otros retiros de las cuasisociedades', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.5.3', N'Arrendamientos de tierras y terrenos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.5.4', N'Otros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.6', N'Ventas de Bienes y Servicios de Entidades del Gobierno Federal/ Ingresos de Explotacion de Entidades Empresariales', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.6.1', N'Venta de establecimientos no de mercado', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.6.2', N'Venta de establecimientos de mercado', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.6.3', N'Derechos administrativos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.7', N'Subsidios y Subvenciones Recibidos por las Entidades Empresariales Públicas', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.7.1', N'Subsidios y Subvenciones Recibidos por las Entidades Empresariales Públicas no financieras', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.7.2', N'Subsidios y Subvenciones Recibidos por las Entidades Empresariales Públicas financieras', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8', N'Transferencias, Asignaciones y Donativos Corrientes Recibidos', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.1', N'Del sector privado', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.2', N'Del sector público', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.2.1', N'De la Federación', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.2.1.1', N'Transferencias Internas y Asignaciones', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.2.1.2', N'Transferencias del resto del Sector Publico', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.2.1.3', N'Pensiones y Jubilaciones', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.2.1.4', N'Transferencias de Fideicomisos, Mandatos y Contratos Analogos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.2.2', N'De Entidades Federativas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.2.3', N'De Municipios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.3', N'Del sector externo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.3.1', N'De gobiernos extranjeros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.3.2', N'De organismos internacionales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.8.3.3', N'Del sector privado externo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.1.9', N'  Participaciones', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2', N'INGRESOS DE CAPITAL', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.1', N'Venta (Disposicion) de Activos', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.1.1', N'Venta de Activos Fijos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.1.2', N'Venta de Objetos de Valor', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.1.3', N'Venta de Activos No Producidos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.2', N'Disminucion de Existencias', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.2.1', N'Materiales y suministros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.2.2', N'Materias Primas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.2.3', N'Trabajos en curso', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.2.4', N'Bienes terminados', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.2.5', N'Bienes para venta', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.2.6', N'Bienes en transito', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.2.7', N'Existencia de material de seguridad y defensa', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.3', N'Incremento de la depreciacion, amortización, estimaciones y provisiones acumuladas', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.3.1', N'Depreciacion y Amortización', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.3.2', N'Estimaciones por Deterioro de Inventarios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.3.3', N'Otras estimaciones por pérdida o deterioro', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.3.4', N'Provisiones  ', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4', N'Transferencias, asignaciones y donativos de capital recibidos ', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.1', N'Del sector privado', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.2', N'Del sector público', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.2.1', N'De la Federación', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.2.1.1', N'Transferencias Internas y Asignaciones', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.2.1.2', N'Transferencias del resto del Sector Publico', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.2.1.3', N'Pensiones y Jubilaciones', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.2.1.4', N'Transferencias de Fideicomisos, Mandatos y Contratos Analogos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.2.2', N'De Entidades Federativas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.2.3', N'De Municipios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.3', N'Del sector externo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.3.1', N'De gobiernos extranjeros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.3.2', N'De organismos internacionales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.4.3.3', N'Del sector privado externo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.5', N'Recuperación de inversiones financieras realizadas con fines de politica', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.5.1', N'Venta de acciones y participaciones de Capital adquiridas con fines de politica', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.5.2', N'Valores representativos de deuda adquiridos con fines de politica', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.5.3', N'Venta de obligaciones negociables adquiridas con fines de politica', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'1.2.5.4', N'Recuperación de préstamos realizados con fines de politica', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'', N'TOTAL INGRESOS', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2', N'GASTOS', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1', N'GASTOS CORRIENTES', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.1', N'Gastos de Consumo de los entes del Gobierno General/ Gastos de Explotación de las entidades empresariales', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.1.1', N'Remuneraciones', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.1.1.1', N'Sueldos y Salarios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.1.1.2', N'Contribuciones Sociales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.1.1.3', N'Impuestos sobre Nóminas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.1.2', N'Compra de bienes y servicios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'', N'', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.1.3', N'Variación de existencias (Disminución (+) Incremento(-))', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.1.4', N'Depreciación y Amortización (Consumo de Capital Fijo)', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.1.5', N'Estimaciones por Deterioro de Inventarios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.1.6', N'Impuestos sobre los productos, la producción y las importaciones de las entidades empresariales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.2', N'Prestaciones de Seguridad Social (MEFP 6.69)', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.3', N'Gastos de la Propiedad', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.3.1', N'Intereses', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.3.1.1', N'Intereses de la deuda interna', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.3.1.2', N'Intereses de la deuda externa', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.3.2', N'Gastos de la Propiedad Distintos de Intereses ', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.3.2.1', N'Dividendos y retiros de las cuasisociedades', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.3.2.2', N'Arrendamientos de tierras y terrenos (MEFP 6.81)', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.4', N'Subsidios y Subvenciones a Empresas (MEFP 6.61)', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.4.1', N'A entidades empresariales del sector privado', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.4.1.1', N'A entidades empresariales no financieras', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.4.1.2', N'A entidades empresariales financieras', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.4.2', N'A entidades empresariales del sector publico', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.4.2.1', N'A entidades empresariales no financieras', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.4.2.2', N'A entidades empresariales financieras', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5', N'Transferencias, asignaciones y donativos corrientes otorgados', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.1', N'Del sector privado', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.1.1', N'Ayuda a Personas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.1.2', N'Becas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.1.3', N'Ayuda a Instituciones', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.1.4', N'Instituciones de Interes Publico', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.1.5', N'Desastres Naturales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.1.6', N'Fideicomisos, Mandatos y Contratos Analogos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.1.7', N'Otras', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.2', N'Del sector público', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.2.1', N'De la Federación', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.2.1.1', N'Transferencias Internas y Asignaciones', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.2.1.2', N'Transferencias del resto del Sector Publico', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.2.1.3', N'organismos de la Seguridad Social', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.2.1.4', N'Transferencias de Fideicomisos, Mandatos y Contratos Analogos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.2.2', N'De Entidades Federativas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.2.3', N'De Municipios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.3', N'Del sector externo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.3.1', N'De gobiernos extranjeros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.3.2', N'De organismos internacionales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.5.3.3', N'Del sector privado externo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.6', N'Impuestos sobre los ingresos, la riqueza y otros a las entidades empresariales públicas', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.7', N'Participaciones', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.8', N'Provisiones y Otras Estimaciones', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.8.1', N'Provisiones a corto plazo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.8.2', N'provisiones a largo plazo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.8.3', N'Estimaciones por perdida o deterioro a corto plazo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.1.8.4', N'Estimaciones por pérdida o deterioro a largo plazo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2', N'GASTOS DE CAPITAL', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.1', N'Construcciones en Proceso', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2', N'Activos Fijos (Formación bruta de Capital Fijo) ', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.1', N'Viviendas, Edificios y Estructuras', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.1.1', N'Viviendas ', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.1.2', N'Edificios no Residenciales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.1.3', N'Otras estructuras', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.2', N'Maquinaria y Equipo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.2.1', N'Equipo de transporte', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.2.2', N'Equipo de tecnologia de la información y comunicaciones', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.2.3', N'Otra maquina y equipo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.3', N'Equipo de Defensa y Seguridad', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.4', N'Activos Biológicos Cultivados', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.4.1', N'Ganado para cría, leche, tiro, etc. Que dan productos recurrentes', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.4.2', N'Arboles, cultivos y otras plantaciones que dan productos recurrentes', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.5', N'Activos Fijos Intangibles', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.5.1', N'Investigación y desarrollo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.5.2', N'Exploración y evaluación minera', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.5.3', N'Programas de informática y bases de datos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.5.4', N'Originales para esparcimiento, literarios o artísticos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.2.5.5', N'Otros activos fijos intangibles', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.3', N'Incremento de existencias', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.3.1', N'Materiales y suministros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.3.2', N'Materias primas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.3.3', N'Trabajos en curso', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.3.4', N'Bienes terminados', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.3.5', N'Bienes para venta', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.3.6', N'Bienes en transito', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.3.7', N'Existencias de materiales de seguridad y defensa', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.4', N'Objetos de valor', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.4.1', N'Metales y piedras preciosas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.4.2', N'Antiguedades y otros objetos de arte', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.4.3', N'Otros objetos de valor', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5', N'Activos no producidos', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.1', N'Activos tangibles no producidos de origen natural', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.1.1', N'Tierras y Terrenos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.1.2', N'Recursos minerales y energeticos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.1.3', N'Recursos biologicos no cultivados', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.1.4', N'Recursos hidricos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.1.5', N'Otros activos de origen natural', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.2', N'Activos intangibles no producidos (MEFP 7.78)', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.2.1', N'Derechos patentados', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.2.2', N'Arrendamientos operativos comerciales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.2.3', N'Fondos de comercio adquiridos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.5.2.4', N'Otros activos intangibles no producidos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6', N'Transferencias, asignaciones y donativos de capital otorgados', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.1', N'Al sector privado', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.1.1', N'Ayuda a Personas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.1.2', N'Ayuda a Instituciones', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.1.3', N'Instituciones de Interes Publico', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.1.4', N'Desastres Naturales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.2', N'Al sector publico', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.2.1', N'A la Federación', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.2.1.1', N'Transferencias Internas y Asignaciones', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.2.1.2', N'Transferencias al resto del Sector Público', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.2.1.3', N'Transferencias de Fideicomisos, Mandatos y Contratos Analogos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.2.2', N'A Entidades Federativas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.2.3', N'A municipios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.3', N'Al sector externo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.3.1', N'A gobiernops extranjeros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.3.2', N'A organismos internacionales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.6.3.3', N'Al sector privado externo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7', N'Inversiónes financieras realizadas con fines de política económica', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.1', N'Acciones y participaciones de capital', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.1.1', N'Interna', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.1.1.1', N'Sector Publico', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.1.1.2', N'Sector Privado', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.1.2', N'Externa', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.2', N'Valores representativos de deuda adquiridos con fines de politica economica', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.3', N'Obligaciones negociables adquiridas con fines de politica económica', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.4', N'Consesión de Prestamos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.4.1', N'Internos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.4.1.1', N'Sector Público', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.4.1.2', N'Sector Privado', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'2.2.7.4.2', N'Externos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'', N'TOTAL GASTO', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'Menos', N'Participaciones, Intereses y Otros Gastos de la Deuda=', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'', N'TOTAL GASTO PROGRAMABLE', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3', N'FINANCIAMIENTO', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1', N'FUENTES FINANCIERAS', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1', N'Disminución de Activos Financieros', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1', N'Disminución de Activos Financieros Corrientes (Circulantes)', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.1', N'Disminución de Caja y Bancos (efectivos y equvalentes)', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.1.1', N'Efectivo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.1.2', N'Bancos/Tesoreria', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.1.3', N'Bancos/Dependencias y otros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.1.4', N'Inversiones Temporales (Hasta 3 meses)', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.1.5', N'Fondos de Afectación Especifica', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.1.6', N'Depositos de Fondos de Terceros en Garantia y Administración', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.1.7', N'Otro Efectivo y Equivalentes', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.2', N'Disminución de Inversiones financieras de corto plazo (derechos a recibir efectivo o equivalentes)', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.2.1', N'Titulos y Valores', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.2.2', N'Acciones y participaciones de capital', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.2.3', N'Otras inversiones Financieras', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.3', N'Disminución de cuentas por cobrar', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.3.1', N'Cuentas por Cobrar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.3.2', N'Deudores Diversos por Cobrar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.3.3', N'Ingresos por Recuperar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.3.4', N'Deudores por Anticipos de la Tesoreria', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.4', N'Disminución de documentos por cobrar', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.4.1', N'Otros derechos a Recibir Efectivo o Equivalentes', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.5', N'Recuperación de préstamos otorgados de corto plazo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.6', N'Disminución de otros activos financieros corrientes', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.6.1', N'Anticipos a Proveedores por Adquisicion de Bienes y Prestación de Servicios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.6.2', N'Anticipos a Proveedores por Adquisicion de Bienes Inmuebles y Muebles', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.6.3', N'Anticipos a Proveedores por Adquisicion de Bienes Intangibles', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.6.4', N'Anticipo a Contratistas por Obras Publicas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.6.5', N'Otros derechos a Recibir Bienes o Servicios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.1.6.6', N'Disminución de Otros Activos Circulantes', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2', N'Disminución de Activos Financieros No Corrientes', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.1', N'Recuperacion de inversiones financieras de largo plazo con fines de liquidez', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.1.1', N'Venta de acciones y participaciones de Capital', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.1.1.1', N'Internos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.1.1.2', N'Externos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.1.2', N'Venta de titulos y valores representativos de deuda', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.1.3', N'Venta de obligaciones negociables  ', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.1.4', N'Recuperación de préstamos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.1.4.1', N'Internos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.1.4.2', N'Externos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.2', N'Disminución de otros activos financieros no corrientes', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.2.1', N'Documentos por Cobrar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.2.2', N'Deudores Diversos  ', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.2.3', N'Otros derechos a Recibir Efectivo o Equivalentes', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.2.4', N'Activos Diferidos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.1.2.2.5', N'Otros Activos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2', N'Incremento de Pasivos', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1', N'Incremento de Pasivos Corrientes', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.1', N'Incremento de cuentas por pagar', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.1', N'Servicios Personales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.2', N'Proveedores por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.3', N'Contratistas por Obras Publicas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.4', N'Participaciones y Aportaciones por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.5', N'Transferencias Otorgadas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.6', N'Intereses y Comisiones por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.7', N'Retenciones y Contribuciones por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.8', N'Devoluciones de Contribuciones por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.9', N'Otras Cuentas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2', N'Incremento de documentos por pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.1', N'Documentos Comercilaes por pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.2', N'Documentos con Contratistas por Obras Publicas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.3', N'Otros Documentos por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.4', N'Titulos y Valores de la Deuda Pública Interna', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.2.5', N'Titulos y Valores de la Deuda Pública Externa', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.3', N'Conversión de la deuda pública a largo plazo en porción circulante', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.3.1', N'Conversión de títulos y valores de largo plazo en corto plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.3.1.1', N'Porción de corto plazo de títulos y valores de la deuda pública interna de L.P.', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.3.1.2', N'Porción de corto plazo de títulos y valores de la deuda pública externa de L.P.', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.3.2', N'Conversión de préstamos de largo plazo en corto plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.3.2.1', N'Porción de corto plazo de préstamos de la deuda pública interna de L.P.', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.3.2.2', N'Porción de corto plazo de préstamos de la deuda pública externa de L.P.', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.4', N'Incremento de otros pasivos de corto plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.4.1', N'Pasivos Diferidos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.4.2', N'Fondos y Bienes de Terceros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.4.3', N'Otros Pasivos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2', N'Incremento de Pasivos No Corrientes', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.1', N'Incremento de cuentas por pagar a largo plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.1.1', N'Proveedores por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.1.2', N'Contratistas por Obras Publicas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.2', N'Incremento de documentos por pagar a largo plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.2.1', N'Documentos Comercilaes por pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.2.2', N'Documentos con Contratistas por Obras Publicas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.2.3', N'Otros Documentos por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.3', N'Colocación de títulos y valores a largo plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.3.1', N'Colocación de títulos y valores de la deuda pública interna', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.3.2', N'Colocación de títulos y valores de la deuda pública interna', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.4', N'Obtención de préstamos de la deuda pública a largo plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.4.1', N'Obtención de préstamos internos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.4.2', N'Obtención de préstamos externos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.5', N'Incremento de otros pasivos de largo plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.5.1', N'Pasivos Diferidos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.5.2', N'Fondos y Bienes de Terceros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.2.5.3', N'Otros Pasivos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.3', N'Incremento de Patrimonio', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'', N'TOTAL DE FUENTES FINANCIERAS', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2', N'APLICACIONES FINANCIERAS (USOS)', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1', N'Incremento en activos financieros', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1', N'Incremento en activos financieros Corrientes (Circulantes)', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.1', N'Incremento de Caja y Bancos (efectivos y equvalentes)', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.1.1', N'Efectivo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.1.2', N'Bancos/Tesoreria', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.1.3', N'Bancos/Dependencias y otros', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.1.4', N'Inversiones Temporales (Hasta 3 meses)', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.1.5', N'Fondos de Afectación Especifica', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.1.6', N'Depositos de Fondos de Terceros en Garantia y Administración', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.1.7', N'Otro Efectivo y Equivalentes', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.2', N'Incrementos de inversiones financieras de corto plazo (derechos a recibir efectivo y equivalentes)', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.2.1', N'Titulos y Valores', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.2.2', N'Acciones y participaciones de capital', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.2.3', N'Otras inversiones Financieras', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.3', N'Incremento de cuentas por cobrar', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.3.1', N'Cuentas por Cobrar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.3.2', N'Deudores Diversos por Cobrar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.3.3', N'Ingresos por Recuperar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.3.4', N'Deudores por Anticipos de la Tesoreria', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.4', N'Incremento de documentos por cobrar', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.4.1', N'Otros derechos a Recibir Efectivo o Equivalentes', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.5', N'Prestamos otorgados a corto plazo', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.6', N'Incremento de otros activos financieros corrientes', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.6.1', N'Anticipos a Proveedores por Adquisicion de Bienes y Prestación de Servicios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.6.2', N'Anticipos a Proveedores por Adquisicion de Bienes Inmuebles y Muebles', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.6.3', N'Anticipos a Proveedores por Adquisicion de Bienes Intangibles', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.6.4', N'Anticipo a Contratistas por Obras Publicas', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.6.5', N'Otros derechos a Recibir Bienes o Servicios', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.1.6.6', N'Disminución de Otros Activos Circulantes', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2', N'Incremento en activos financieros No Corrientes', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.1', N'Inversiones financieras a largo plazo con fines de liquidez', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.1.1', N'Compra de acciones y participaciones de capital', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.1.1.1', N'Internos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.1.1.2', N'Externos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.1.2', N'Compra de títulos y valores representativos de deuda', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.1.3', N'Compra de obligaciones negociables', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.1.4', N'Conseción de préstamos', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.1.4.1', N'Internos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.1.4.2', N'Externos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.2', N'Incremento de otros activos financieros no corrientes', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.2.1', N'Documentos por Cobrar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.2.2', N'Deudores Diversos  ', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.2.3', N'Otros derechos a Recibir Efectivo o Equivalentes', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.2.4', N'Activos Diferidos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.1.2.2.5', N'Otros Activos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2', N'Disminución de Pasivos', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1', N'Disminucion de Pasivos Corrientes', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.1', N'Disminución de cuentas por pagar', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.1.1', N'Servicios Personales', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.1.2', N'Proveedores por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.1.3', N'Contratistas por Obras Publicas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.1.4', N'Participaciones y Aportaciones por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.1.5', N'Transferencias Otorgadas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.1.6', N'Intereses y Comisiones por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.1.7', N'Retenciones y Contribuciones por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.1.8', N'Devoluciones de Contribuciones por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.1.9', N'Otras Cuentas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.2', N'Disminución de documentos por pagar', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.2.1', N'Documentos Comercilaes por pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.2.2', N'Documentos con Contratistas por Obras Publicas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.2.3', N'Otros Documentos por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.2.4', N'Titulos y Valores de la Deuda Pública Interna', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.2.5', N'Titulos y Valores de la Deuda Pública Externa', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.3', N'Amortización de la Porción Circulante de la Deuda Pública de Largo Plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.3.1', N'Amortización de la Porción Circulante de la Deuda Pública de L.P. en títulos y valores', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.3.1.1', N'Amortización de la Porción Circulante de la Deuda Pública interna de L.P. en títulos y valores', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.3.1.2', N'Amortización de la Porción Circulante de la Deuda Pública externa de L.P. en títulos y valores', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.3.2', N'Amortización de la Porción Circulante de la Deuda Pública de L.P. en préstamos', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.3.2.1', N'Amortización de la Porción Circulante de la Deuda Pública interna de L.P. en préstamos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.1.3.2.2', N'Amortización de la Porción Circulante de la Deuda Pública externa de L.P. en préstamos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.4', N'Disminucion de Otros Pasivos de Corto Plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.4.1', N'Pasivos Diferidos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.4.2', N'Fondos y Bienes de Terceros en Garantia y/o Administración', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.1.2.1.4.3', N'Otros Pasivos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2', N'Disminucion de Pasivos no Corrientes', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.1', N'Disminucion de Cuentas por Pagar a Largo Plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.1.1', N'Proveedores por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.1.2', N'Contratistas por Obras Publicas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.2', N'Disminucion de Documentos por Pagar a Largo Plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.2.1', N'Documentos Comercilaes por pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.2.2', N'Documentos con Contratistas por Obras Publicas por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.2.3', N'Otros Documentos por Pagar', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.3', N'Conversión de deuda Pública de Largo Plazo en Porción Circulante', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.3.1', N'Conversión de titulos y valores de largo plazo en corto plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.3.1.1', N'Porcion de corto plazo de titulos y valores de la deuda pública interna', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.3.1.2', N'Porcion de corto plazo de titulos y valores de la deuda pública externa', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.3.2', N'Conversión de préstamos de largo plazo en corto plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.3.2.1', N'Porcion de corto plazo de préstamos de la deuda pública interna', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.3.2.2', N'Porcion de corto plazo de préstamos de la deuda pública externa', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.4', N'Disminución de Otros Pasivos de largo Plazo', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.4.1', N'Pasivos Diferidos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.4.2', N'Fondos y Bienes de Terceros en Garantia y/o Administración', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.2.2.4.3', N'Otros Pasivos', N'',0)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'3.2.3', N'Disminución de Patrimonio', N'',1)
INSERT INTO @Tabla ([Codigo], [Concepto], [Nota1],[Negritas]) VALUES (N'', N'TOTAL APLICACIONES FINANCIERAS', N'',1)

UPDATE @Tabla set Nota1 = (Select Codigo + ' Click Aqui...')
UPDATE @Tabla set Nota1 =(Select Concepto + ' Click Aqui...') where Codigo=''

Select * from @Tabla


GO
Update C_Menu set Utilizar=1 where idmenu=1164
GO

