-- Cambios a la BD de Kórima originados por las reformas CONAC del 27/09/2018

-- Actualización de nombres de cuentas y descripciones, del plan de cuentas ya existente
UPDATE C_Contable SET NombreCuenta='Cuotas para la Seguridad Social', Descripcion='Importe de los ingresos que reciben los entes públicos que prestan los servicios de seguridad social, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1031;
UPDATE C_Contable SET NombreCuenta='Productos', Descripcion='Comprende el importe de los ingresos por contraprestaciones por los servicios que preste el Estado en sus funciones de derecho privado.' WHERE IdCuentaContable=213;
UPDATE C_Contable SET NombreCuenta='Productos', Descripcion='Importe de los ingresos por concepto de servicios otorgados por funciones de derecho privado, tales como los intereses que generan las cuentas bancarias de los entes públicos, entre otros, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1039;
UPDATE C_Contable SET NombreCuenta='Aprovechamientos', Descripcion='Comprende el importe de los ingresos que percibe el Estado por funciones de derecho público distintos de las contribuciones, los ingresos derivados de financiamientos y de los que obtengan los organismos descentralizados y las empresas de participación estatal y municipal.' WHERE IdCuentaContable=218;
UPDATE C_Contable SET NombreCuenta='Aprovechamientos no Comprendidos en la Ley de Ingresos Vigente, Causados en Ejercicios Fiscales Anteriores Pendientes de Liquidación o Pago', Descripcion='Importe de los ingresos que se recaudan en el ejercicio corriente, por aprovechamientos pendientes de liquidación o pago causados en ejercicios fiscales anteriores, no incluidos en la Ley de Ingresos vigente.' WHERE IdCuentaContable=1225;
UPDATE C_Contable SET NombreCuenta='Ingresos por Venta de Bienes y Prestación de Servicios', Descripcion='Comprende el importe de los ingresos propios obtenidos por las Instituciones Públicas de Seguridad Social, las Empresas Productivas del Estado, las entidades de la administración pública paraestatal y paramunicipal, los poderes legislativo y judicial, y los órganos autónomos federales y estatales, por sus actividades de producción, comercialización o prestación de servicios; así como otros ingresos por sus actividades diversas no inherentes a su operación, que generen recursos.' WHERE IdCuentaContable=1027;
UPDATE C_Contable SET NombreCuenta='Cuotas de Ahorro para el Retiro', Descripcion='Importe de los ingresos que reciben los entes públicos que prestan los servicios de seguridad social, para cubrir las obligaciones relativas a fondos del ahorro para el retiro, de conformidad con la legislación aplicable en la materia'  WHERE IdCuentaContable=1032;
UPDATE C_Contable SET NombreCuenta='Ingresos por Venta de Bienes y Prestación de Servicios de Instituciones Públicas de Seguridad Social', Descripcion='Importe de los ingresos propios obtenidos por las Instituciones Públicas de Seguridad Social por sus actividades de producción, comercialización o prestación de servicios.' WHERE IdCuentaContable=1049;
UPDATE C_Contable SET NombreCuenta='Ingresos por Venta de Bienes y Prestación de Servicios de Empresas Productivas del Estado', Descripcion='Importe de los ingresos propios obtenidos por las Empresas Productivas del Estado por sus actividades de producción, comercialización o prestación de servicios.' WHERE IdCuentaContable=1050;
UPDATE C_Contable SET NombreCuenta='Ingresos por Venta de Bienes y Prestación de Servicios de Entidades Paraestatales y Fideicomisos No Empresariales y No Financieros', Descripcion='Importe de los ingresos propios obtenidos por las Entidades Paraestatales y Fideicomisos No Empresariales y No Financieros por sus actividades de producción, comercialización o prestación de servicios.' WHERE IdCuentaContable=1051;
UPDATE C_Contable SET NombreCuenta='Ingresos por Venta de Bienes y Prestación de Servicios de Entidades Paraestatales Empresariales No Financieras con Participación Estatal Mayoritaria', Descripcion='Importe de los ingresos propios obtenidos por las Entidades Paraestatales Empresariales No Financieras con Participación Estatal Mayoritaria por sus actividades de producción, comercialización o prestación de servicios.' WHERE IdCuentaContable=1052;
UPDATE C_Contable SET NombreCuenta='Participaciones, Aportaciones, Convenios, Incentivos Derivados de la Colaboración Fiscal, Fondos Distintos de Aportaciones, Transferencias, Asignaciones, Subsidios y Subvenciones, y Pensiones y Jubilaciones', Descripcion='Comprende el importe de los recursos que reciben las Entidades Federativas y Municipios por concepto de participaciones, aportaciones, convenios, incentivos derivados de la colaboración fiscal, fondos distintos de aportaciones; así como los ingresos de los entes públicos que provenientes de transferencias, asignaciones, subsidios y subvenciones, y pensiones y jubilaciones.' WHERE IdCuentaContable=1055;
UPDATE C_Contable SET NombreCuenta='Participaciones, Aportaciones, Convenios, Incentivos Derivados de la Colaboración Fiscal y Fondos Distintos de Aportaciones', Descripcion='Comprende el importe de los recursos que reciben las Entidades Federativas y los Municipios por concepto de participaciones, aportaciones, convenios, incentivos derivados de la colaboración fiscal y fondos distintos de aportaciones.' WHERE IdCuentaContable=1056;
UPDATE C_Contable SET NombreCuenta='Transferencias, Asignaciones, Subsidios y Subvenciones, y Pensiones y Jubilaciones', Descripcion='Comprende el importe de los recursos que reciben en forma directa o indirecta los entes públicos como parte de su política económica y social, de acuerdo a las estrategias y prioridades de desarrollo para el sostenimiento y desempeño de sus actividades.' WHERE IdCuentaContable=1057;
UPDATE C_Contable SET NombreCuenta='Transferencias y Asignaciones', Descripcion='Importe de los ingresos que reciben los entes públicos con el objeto de sufragar gastos inherentes a sus atribuciones.' WHERE IdCuentaContable=1061;
UPDATE C_Contable SET NombreCuenta='Intereses Ganados de Títulos, Valores y demás Instrumentos Financieros', Descripcion='Importe de los ingresos obtenidos por concepto de intereses ganados por la posesión de títulos, valores y demás instrumentos financieros.' WHERE IdCuentaContable=224;
UPDATE C_Contable SET NombreCuenta='Disminución del Exceso de Provisiones', Descripcion='Monto de la disminución de la provisión que se establece anualmente por contingencia de pasivos.' WHERE IdCuentaContable=1077;

-- Actualización de solo descripciones, del plan de cuentas ya existente
UPDATE C_Contable SET Descripcion='Representa el monto de las donaciones en especie, recibidas con el fin de dotar al ente público de activos necesarios para su funcionamiento.' WHERE IdCuentaContable=998;
UPDATE C_Contable SET Descripcion='Representa el importe de los ingresos y otros beneficios del ente público provenientes de ingresos de gestión, participaciones, aportaciones, convenios, incentivos derivados de la colaboración fiscal, fondos distintos de aportaciones, transferencias, asignaciones, subsidios y subvenciones, pensiones y jubilaciones, y otros ingresos y beneficios.' WHERE IdCuentaContable=193;
UPDATE C_Contable SET Descripcion='Comprende el importe de los ingresos provenientes de contribuciones, productos, aprovechamientos, así como de venta de bienes y prestación de servicios.' WHERE IdCuentaContable=194;
UPDATE C_Contable SET Descripcion='Comprende el importe de las contribuciones establecidas en Ley que deben pagar las personas físicas y/o morales, que se encuentran en la situación jurídica o de hecho prevista por la misma y que sean distintas de las aportaciones de seguridad social, contribuciones de mejoras y derechos.' WHERE IdCuentaContable=1016;
UPDATE C_Contable SET Descripcion='Importe de las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan sobre los ingresos de las personas físicas y/o morales, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1017;
UPDATE C_Contable SET Descripcion='Importe de las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan sobre los bienes propiedad de las personas físicas y/o morales, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1018;
UPDATE C_Contable SET Descripcion='Importe de las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan sobre la actividad económica relacionada con la producción, el consumo y las transacciones que realizan las personas físicas y/o morales, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1019;
UPDATE C_Contable SET Descripcion='Importe de las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan sobre las actividades de importación y/o exportación que realizan las personas físicas y/o morales, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1020;
UPDATE C_Contable SET Descripcion='Importe de las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan sobre la base gravable de las remuneraciones al trabajo personal subordinado o el que corresponda, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1021;
UPDATE C_Contable SET Descripcion='Importe de las contribuciones derivadas de las imposiciones fiscales que en forma unilateral y obligatoria se fijan a las personas físicas y/o morales, por la afectación preventiva o correctiva que se ocasione en flora, fauna, medio ambiente o todo aquello relacionado a la ecología, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1022;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que se perciben por conceptos de recargos, sanciones, gastos de ejecución, indemnizaciones, ente otros, asociados a los impuestos, cuando éstos no se cubran oportunamente, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1023;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que se perciben por conceptos no incluidos en las cuentas anteriores, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1024;
UPDATE C_Contable SET Descripcion='Comprende el importe de las contribuciones establecidas en Ley a cargo de personas que son sustituidas por el Estado en el cumplimiento de obligaciones fijadas por la Ley en materia de seguridad social o a las personas que se beneficien en forma especial por servicios de seguridad social proporcionados por el mismo Estado.' WHERE IdCuentaContable=1025;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que reciben los entes públicos que prestan los servicios de seguridad social, para cubrir las obligaciones relativas a los fondos de vivienda, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1030;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que reciben los entes públicos que prestan los servicios de seguridad social, para cubrir las obligaciones relativas a fondos del ahorro para el retiro, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1032;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que se perciben por concepto de recargos, sanciones, gastos de ejecución, indemnizaciones, entre otros, asociados a las cuotas y aportaciones de seguridad social, cuando éstas no se cubran oportunamente, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1033;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que reciben los entes públicos que prestan los servicios de seguridad social, por conceptos no incluidos en las cuentas anteriores, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1034;
UPDATE C_Contable SET Descripcion='Comprende el importe de las contribuciones establecidas en Ley a cargo de las personas físicas y/o morales que se beneficien de manera directa por obras públicas.' WHERE IdCuentaContable=1026;
UPDATE C_Contable SET Descripcion='Importe de las contribuciones derivadas de los beneficios diferenciales particulares por la realización de obras públicas a cargo de las personas físicas y/o morales, independientemente de la utilidad general colectiva, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1029;
UPDATE C_Contable SET Descripcion='Comprende el importe de las contribuciones establecidas en Ley por el uso o aprovechamiento de los bienes del dominio público, así como por recibir servicios que presta el Estado en sus funciones de derecho público, excepto cuando se presten por organismos descentralizados u órganos desconcentrados cuando en este último caso, se trate de contraprestaciones que no se encuentren previstas en las leyes correspondientes. También son derechos las contribuciones a cargo de los organismos públicos descentralizados por prestar servicios exclusivos del Estado.' WHERE IdCuentaContable=195;
UPDATE C_Contable SET Descripcion='Importe de las contribuciones derivadas de la contraprestación del uso, goce, aprovechamiento o explotación de bienes de dominio público, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1035;
UPDATE C_Contable SET Descripcion='Importe de las contribuciones derivadas por la contraprestación de servicios exclusivos del Estado, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=196;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que se perciben por concepto de recargos, sanciones, gastos de ejecución, indemnizaciones, entre otros, asociados a los derechos, cuando éstos no se cubran oportunamente, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1037;
UPDATE C_Contable SET Descripcion='Comprende el importe de las contribuciones derivadas por contraprestaciones no incluidas en las cuentas anteriores, de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1038;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que se perciben por funciones de derecho público, cuyos elementos pueden no estar previstos en una Ley sino, en una disposición administrativa de carácter general, provenientes de multas no fiscales.' WHERE IdCuentaContable=1043;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que se perciben por funciones de derecho público, cuyos elementos pueden no estar previstos en una Ley sino, en una disposición administrativa de carácter general, provenientes de indemnizaciones no fiscales.' WHERE IdCuentaContable=1044;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que se perciben por funciones de derecho público, cuyos elementos pueden no estar previstos en una Ley sino, en una disposición administrativa de carácter general, provenientes de reintegros.' WHERE IdCuentaContable=1045;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que se perciben por funciones de derecho público, cuyos elementos pueden no estar previstos en una Ley sino, en una disposición administrativa de carácter general, provenientes de obras públicas que realiza un ente público.' WHERE IdCuentaContable=1046;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que se perciben por concepto de recargos, sanciones, gastos de ejecución e indemnizaciones, entre otros, asociados a los aprovechamientos, cuando éstos no se cubran oportunamente de conformidad con la legislación aplicable en la materia.' WHERE IdCuentaContable=1048;
UPDATE C_Contable SET Descripcion='Comprende el importe de los ingresos que se perciben por aprovechamientos no incluidos en las cuentas anteriores, tales como aplicación de gravámenes sobre herencias, legados y donaciones, servicio del sistema escolar federalizado, juegos y sorteos, donativos en efectivo del Poder Ejecutivo, patrimonio invertido del Poder Ejecutivo, explotación de obras del dominio público, servicios públicos, entre otros, de conformidad con las disposiciones aplicables.' WHERE IdCuentaContable=219;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que reciben las Entidades Federativas y Municipios que se derivan de la adhesión al Sistema Nacional de Coordinación Fiscal, así como las que correspondan a sistemas estatales de coordinación fiscal, determinados por las leyes correspondientes.' WHERE IdCuentaContable=1058;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que reciben las Entidades Federativas y Municipios previstos en la Ley de Coordinación Fiscal, cuyo gasto está condicionado a la consecución y cumplimiento de los objetivos que para cada tipo de aportación establece la legislación aplicable en la materia.' WHERE IdCuentaContable=1059;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que reciben las Entidades Federativas y Municipios derivados de convenios de coordinación, colaboración, reasignación o descentralización según corresponda, los cuales se acuerdan entre la Federación, las Entidades Federativas y/o los Municipios.' WHERE IdCuentaContable=1060;
UPDATE C_Contable SET Descripcion='Importe de los ingresos para el desarrollo de actividades prioritarias de interés general, que reciben los entes públicos mediante asignación directa de recursos, con el fin de favorecer a los diferentes sectores de la sociedad para apoyar en sus operaciones, mantener los niveles en los precios, apoyar el consumo, la distribución y comercialización de bienes, motivar la inversión, cubrir impactos financieros, promover la innovación tecnológica, y para el fomento de las actividades agropecuarias, industriales o de servicios.' WHERE IdCuentaContable=1063;
UPDATE C_Contable SET Descripcion='Importe de los ingresos que reciben los entes públicos de seguridad social, que cubre el Gobierno Federal, Estatal o Municipal según corresponda, por el pago de pensiones y jubilaciones.' WHERE IdCuentaContable=1065;
UPDATE C_Contable SET Descripcion='Comprende el importe de otros ingresos y beneficios obtenidos por los entes públicos, así como otros ingresos propios obtenidos por los Poderes Legislativo y Judicial, los Órganos Autónomos y las entidades de la administración pública paraestatal y paramunicipal por sus actividades diversas no inherentes a su operación que generan recursos y que no sean ingresos por venta de bienes o prestación de servicios.' WHERE IdCuentaContable=222;
UPDATE C_Contable SET Descripcion='Comprende el importe de los ingresos por concepto de intereses ganados por la posesión de títulos, valores y demás instrumentos financieros, entre otros.' WHERE IdCuentaContable=223;
UPDATE C_Contable SET Descripcion='Importe de los ingresos financieros obtenidos, no incluidos en la cuenta anterior.' WHERE IdCuentaContable=1066;
UPDATE C_Contable SET Descripcion='Comprende la diferencia a favor entre el resultado en libros y el real de las existencias de inventarios al fin de cada período.' WHERE IdCuentaContable=1067;
UPDATE C_Contable SET Descripcion='Monto de la diferencia a favor entre el resultado en libros y el real de las existencias de mercancías para venta al fin de cada período.' WHERE IdCuentaContable=1071;
UPDATE C_Contable SET Descripcion='Monto de la diferencia a favor entre el resultado en libros y el real de las existencias de mercancías terminadas al fin de cada período.' WHERE IdCuentaContable=1072;
UPDATE C_Contable SET Descripcion='Monto de la diferencia a favor entre el resultado en libros y el real de existencias de mercancías en proceso de elaboración al fin de cada período.' WHERE IdCuentaContable=1073;
UPDATE C_Contable SET Descripcion='Monto de la diferencia a favor entre el resultado en libros y el real de existencias de materias primas, materiales y suministros para producción al fin de cada período.' WHERE IdCuentaContable=1074;
UPDATE C_Contable SET Descripcion='Monto de la diferencia a favor entre el resultado en libros y el real de existencias de materias primas, materiales y suministros de consumo al fin de cada período.' WHERE IdCuentaContable=1075;
UPDATE C_Contable SET Descripcion='Comprende la disminución de la estimación por pérdida o deterioro u obsolescencia que se establece anualmente por contingencia de activos.' WHERE IdCuentaContable=1068;
UPDATE C_Contable SET Descripcion='Monto de la disminución de la estimación por pérdida o deterioro u obsolescencia que se establece anualmente por contingencia de activos.' WHERE IdCuentaContable=1076;
UPDATE C_Contable SET Descripcion='Comprende la disminución de la provisión que se establece anualmente por contingencia de pasivos.' WHERE IdCuentaContable=1069;
UPDATE C_Contable SET Descripcion='Comprende el importe de otros ingresos y beneficios varios no incluidos en los rubros anteriores, obtenidos por los entes públicos, como es la utilidad por venta de bienes inmuebles, muebles e intangibles sobre la par, entre otros; asimismo, considera los otros ingresos propios obtenidos por los Poderes Legislativo y Judicial, los Órganos Autónomos y las entidades de la administración pública paraestatal y paramunicipal por sus actividades diversas no inherentes a su operación que generan recurso, tales como donativos en efectivo, entre otros.' WHERE IdCuentaContable=1070;
UPDATE C_Contable SET Descripcion='Monto de la diferencia a favor entre los activos y pasivos monetarios del ente público, siempre que el efecto no haya sido capitalizado en algún activo o pasivo no monetario específico reexpresado.' WHERE IdCuentaContable=1082;
UPDATE C_Contable SET Descripcion='Importe de otros ingresos y beneficios varios no incluidos en las cuentas anteriores, obtenidos por los entes públicos, como es la utilidad por venta de bienes inmuebles, muebles e intangibles sobre la par, entre otros; asimismo, considera los otros ingresos propios obtenidos por los Poderes Legislativo y Judicial, los Órganos Autónomos y las entidades de la administración pública paraestatal y paramunicipal por sus actividades diversas no inherentes a su operación que generan recurso, tales como donativos en efectivo, entre otros.' WHERE IdCuentaContable=1084;
UPDATE C_Contable SET Descripcion='Importe en contra por el tipo de cambio de la moneda con respecto a la de otro país.' WHERE IdCuentaContable=1162;
UPDATE C_Contable SET Descripcion='Representa el importe que se aprueba anualmente en la Ley de Ingresos, e incluyen los impuestos, cuotas y aportaciones de seguridad social, contribuciones de mejoras, derechos, productos, aprovechamientos, ingresos por venta de bienes y prestación de servicios, participaciones, aportaciones, convenios, incentivos derivados de la colaboración fiscal, fondos distintos de aportaciones, transferencias, asignaciones, subsidios y subvenciones, pensiones y jubilaciones, ingresos derivados de financiamientos, y otros ingresos.' WHERE IdCuentaContable=1212;
UPDATE C_Contable SET Descripcion='Representa los ingresos estimados incluyendo las modificaciones por ampliaciones y reducciones autorizadas, así como, los ingresos devengados.' WHERE IdCuentaContable=1213;
UPDATE C_Contable SET Descripcion='Representa los derechos de cobro de los impuestos, cuotas y aportaciones de seguridad social, contribuciones de mejoras, derechos, productos, aprovechamientos, ingresos por venta de bienes y prestación de servicios, participaciones, aportaciones, convenios, incentivos derivados de la colaboración fiscal, fondos distintos de aportaciones, transferencias, asignaciones, subsidios y subvenciones, pensiones y jubilaciones, ingresos derivados de financiamientos, y otros ingresos. En el caso de resoluciones en firme (definitivas) y pago en parcialidades se deberán reconocer y registrar cuando ocurre la notificación de la resolución y/o en la firma del convenio de pago en parcialidades, respectivamente. Su saldo representa la Ley de Ingresos Devengada pendiente de recaudar.' WHERE IdCuentaContable=1215;
UPDATE C_Contable SET Descripcion='Representa el cobro en efectivo o por cualquier otro medio de pago de los impuestos, cuotas y aportaciones de seguridad social, contribuciones de mejoras, derechos, productos, aprovechamientos, ingresos por venta de bienes y prestación de servicios, participaciones, aportaciones, convenios, incentivos derivados de la colaboración fiscal, fondos distintos de aportaciones, transferencias, asignaciones, subsidios y subvenciones, pensiones y jubilaciones, ingresos derivados de financiamientos, y otros ingresos.' WHERE IdCuentaContable=1216;

declare @Estructura1 as int
declare @Estructura2 as int
set @Estructura1= Convert(Int,SUBSTRING((SELECT TOP(1) VALOR FROM T_PARAMETROSCONTABLES WHERE NOMBREPARAMETRO = 'ESTRUCTURA CONTABLE'),1,1))
set @Estructura2= Convert (Int,SUBSTRING((SELECT TOP(1) VALOR FROM T_PARAMETROSCONTABLES WHERE NOMBREPARAMETRO = 'ESTRUCTURA CONTABLE'),3,1))
declare @CerosEstructura varchar(20)
set @CerosEstructura = REPLICATE('0',@Estructura2)

SELECT @Estructura1,@Estructura2,@CerosEstructura , '4118'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'411'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura;

-- Creación de cuentas nuevas (VIGENTES A PARTIR DE 01-01-2019)
DELETE FROM [C_Contable] WHERE IdCuentaContable IN (678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701);
INSERT INTO [dbo].[C_Contable]
([IdCuentaContable],[IdPartidaGI],[NumeroCuenta],[NombreCuenta],[IdCuentaAfectacion],[CuentaAcumulacion],[TipoCuenta],[Afectable],[Nivel],[Alta],[Exportada],[Financiero],[AfectaDisponibilidad],[IdSelloPresupuestal],[IdCuentaContableMayor],[Utilizar],[Armonizado],[Observaciones],[SuSaldoRepresenta],[Descripcion],[Fecha],[SaldarCierreEjercicio],[CrearSubcuentasAutomaticas],[FechaAuditoria],[HoraAuditoria],[IdUsuarioModifica])
     VALUES
 (678,0,'4118'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Impuestos no Comprendidos en la Ley de Ingresos Vigente, Causados en Ejercicios Fiscales Anteriores Pendientes de Liquidación o Pago',1016,'411'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de los ingresos que se recaudan en el ejercicio corriente, por impuestos pendientes de liquidación o pago causados en ejercicios fiscales anteriores, no incluidos en la Ley de Ingresos vigente.','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(679,0,'4132'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Contribuciones de Mejoras no Comprendidas en la Ley de Ingresos Vigente, Causadas en Ejercicios Fiscales Anteriores Pendientes de Liquidación o Pago',1026,'413'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de los ingresos que se recaudan en el ejercicio corriente, por contribuciones de mejoras pendientes de liquidación o pago causadas en ejercicios fiscales anteriores, no incluidas en la Ley de Ingresos vigente.','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(680,0,'4145'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Derechos no Comprendidos en la Ley de Ingresos Vigente, Causados en Ejercicios Fiscales Anteriores Pendientes de Liquidación o Pago',195,'414'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de las contribuciones que se recaudan en el ejercicio corriente, por derechos pendientes de liquidación o pago causados en ejercicios fiscales anteriores, no incluidos en la Ley de Ingresos vigente.','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(681,0,'4154'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Productos no Comprendidos en la Ley de Ingresos Vigente, Causados en Ejercicios Fiscales Anteriores Pendientes de Liquidación o Pago',213,'415'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de los ingresos que se recaudan en el ejercicio corriente, por productos pendientes de liquidación o pago causados en ejercicios fiscales anteriores, no incluidos en la Ley de Ingresos vigente.','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(682,0,'4175'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Ingresos por Venta de Bienes y Prestación de Servicios de Entidades Paraestatales Empresariales Financieras Monetarias con Participación Estatal Mayoritaria',1027,'417'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de los ingresos propios obtenidos por las Entidades Paraestatales Empresariales Financieras Monetarias con Participación Estatal Mayoritaria por sus actividades de producción, comercialización o prestación de servicios.','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(683,0,'4176'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Ingresos por Venta de Bienes y Prestación de Servicios de Entidades Paraestatales Empresariales Financieras No Monetarias con Participación Estatal Mayoritaria',1027,'417'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de los ingresos propios obtenidos por las Entidades Paraestatales Empresariales Financieras No Monetarias con Participación Estatal Mayoritaria por sus actividades de producción, comercialización o prestación de servicios.','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(684,0,'4177'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Ingresos por Venta de Bienes y Prestación de Servicios de Fideicomisos Financieros Públicos con Participación Estatal Mayoritaria',1027,'417'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de los ingresos propios obtenidos por los Fideicomisos Financieros Públicos con Participación Estatal Mayoritaria por sus actividades de producción, comercialización o prestación de servicios.','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(685,0,'4178'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Ingresos por Venta de Bienes y Prestación de Servicios de los Poderes Legislativo y Judicial,  y de los Órganos Autónomos',1027,'417'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de los ingresos propios obtenidos por los Poderes Legislativo y Judicial, y los Órganos Autónomos por sus actividades de producción, comercialización  o prestación de servicios.','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(686,0,'4214'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Incentivos Derivados de la Colaboración Fiscal',1056,'421'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de los ingresos que reciben las Entidades Federativas y Municipios derivados del ejercicio de facultades delegadas por la Federación mediante la celebración de convenios de colaboración administrativa en materia fiscal; que comprenden las funciones de recaudación, fiscalización y administración de ingresos federales y por las que a cambio reciben incentivos económicos que implican la retribución de su colaboración.','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(687,0,'4215'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Fondos Distintos de Aportaciones',1056,'421'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de los ingresos que reciben las Entidades Federativas y Municipios derivados de fondos distintos de aportaciones y previstos en disposiciones específicas, tales como: Fondo para Entidades Federativas y Municipios Productores de Hidrocarburos, y Fondo para el Desarrollo Regional Sustentable de Estados y Municipios Mineros (Fondo Minero), entre otros','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(688,0,'4227'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Transferencias del Fondo Mexicano del Petróleo para la Estabilización y el Desarrollo',1057,'422'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe de los ingresos que reciben los entes públicos por transferencias del Fondo Mexicano del Petróleo para la Estabilización y el Desarrollo.','2018-27-09 00:00:00.000',1,1,NULL,NULL,NULL)
,(689,0,'4397'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Diferencias por Reestructuración de Deuda Pública a Favor',1070,'439'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'H',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe a favor por la reestructuración de la Deuda Pública.','2018-27-09 00:00:00.000',1,NULL,NULL,NULL,NULL)
,(690,0,'5598'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'Diferencias por Reestructuración de Deuda Pública Negativas',1110,'559'+Replicate('0',@Estructura1-3)+'-'+@CerosEstructura,'G',1,3,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,'Importe en contra por la reestructuración de la Deuda Pública.','2018-27-09 00:00:00.000',1,NULL,NULL,NULL,NULL)
,(691,0,'11261'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Préstamos Otorgados a CP al Sector Público',70,'1126'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'A',1,4,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,NULL,'2018-27-09 00:00:00.000',NULL,NULL,NULL,NULL,NULL)
,(692,0,'11262'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Préstamos Otorgados a CP al Sector Privado',70,'1126'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'A',1,4,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,NULL,'2018-27-09 00:00:00.000',NULL,NULL,NULL,NULL,NULL)
,(693,0,'11263'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Préstamos Otorgados a CP al Sector Externo',70,'1126'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'A',1,4,0,0,2,0,0,0,1,0,'Cuenta contable vigente a partir de 01-01-2019',NULL,NULL,'2018-27-09 00:00:00.000',NULL,NULL,NULL,NULL,NULL)
,(694,0,'11213'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Fideicomisos, Mandatos y Contratos Análogos a CP',796,'1121'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'A',1,4,0,0,2,0,0,0,1,1,'Cuenta contable añadida en reformas a Guías Conatbilizadoras del 27-09-18',NULL,NULL,'2018-27-09 00:00:00.000',NULL,NULL,NULL,NULL,NULL)

,(695,0,'21111'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Remuneración por pagar al Personal de carácter permanente a CP',153,'2111'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'D',1,4,0,0,2,0,0,0,1,1,NULL,NULL,NULL,'2017-27-12 00:00:00.000',NULL,NULL,NULL,NULL,NULL)
,(696,0,'21112'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Remuneración por pagar al Personal de carácter transitorio a CP',153,'2111'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'D',1,4,0,0,2,0,0,0,1,1,NULL,NULL,NULL,'2017-27-12 00:00:00.000',NULL,NULL,NULL,NULL,NULL)
,(697,0,'21113'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Remuneraciones Adicionales y Especiales por Pagar a CP',153,'2111'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'D',1,4,0,0,2,0,0,0,1,1,NULL,NULL,NULL,'2017-27-12 00:00:00.000',NULL,NULL,NULL,NULL,NULL)
,(698,0,'21114'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Seguridad Social y Seguros por pagar a CP',153,'2111'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'D',1,4,0,0,2,0,0,0,1,1,NULL,NULL,NULL,'2017-27-12 00:00:00.000',NULL,NULL,NULL,NULL,NULL)
,(699,0,'21115'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Otras prestaciones sociales y económicas por pagar a CP',153,'2111'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'D',1,4,0,0,2,0,0,0,1,1,NULL,NULL,NULL,'2017-27-12 00:00:00.000',NULL,NULL,NULL,NULL,NULL)
,(700,0,'21116'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Estímulos a servidores públicos por pagar a CP',153,'2111'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'D',1,4,0,0,2,0,0,0,1,1,NULL,NULL,NULL,'2017-27-12 00:00:00.000',NULL,NULL,NULL,NULL,NULL)

,(701,0,'21121'+Replicate('0',@Estructura1-5)+'-'+@CerosEstructura,'Deudas por Adquisición de Bienes y Contratación de Servicios por Pagar a CP',156,'2112'+Replicate('0',@Estructura1-4)+'-'+@CerosEstructura,'D',1,4,0,0,2,0,0,0,1,1,NULL,NULL,NULL,'2017-27-12 00:00:00.000',NULL,NULL,NULL,NULL,NULL)


;
-- Hacer no afectable la cuenta de acumulación de la 11213
UPDATE C_Contable SET Afectable=0 WHERE IdCuentaContable=796;

--  Actualización por Derogación de cuentas contables, del plan de cuentas ya existentes (PARA BD EN USO: APLICAR HASTA DESPUES DE REALIZAR EL CIERRE CONTABLE 2018)
-- IF (SELECT GETDATE())>='2019-01-01 04:04:12.607'
-- 	BEGIN
UPDATE C_Contable SET NombreCuenta='Derechos a los Hidrocarburos (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1036;
UPDATE C_Contable SET NombreCuenta='Enajenación de Bienes Muebles no Sujetos a ser Inventariados (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1040;
UPDATE C_Contable SET NombreCuenta='Accesorios de Productos (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1041;
UPDATE C_Contable SET NombreCuenta='Otros Productos que Generan Ingresos Corrientes (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=214;
UPDATE C_Contable SET NombreCuenta='Incentivos Derivados de la Colaboración Fiscal (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1042;
UPDATE C_Contable SET NombreCuenta='Aprovechamientos por Aportaciones y Cooperaciones (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1047;
UPDATE C_Contable SET NombreCuenta='Ingresos no Comprendidos en las Fracciones de la Ley de Ingresos Causados en Ejercicios Fiscales Anteriores Pendientes de Liquidación o Pago (Derogado)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1028;
UPDATE C_Contable SET NombreCuenta='Impuestos no Comprendidos en las Fracciones de la Ley de Ingresos Causados en Ejercicios Fiscales Anteriores Pendientes de Liquidación o Pago (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1053;
UPDATE C_Contable SET NombreCuenta='Contribuciones de Mejoras, Derechos, Productos y Aprovechamientos no Comprendidos en las Fracciones de la Ley de Ingresos Causados en Ejercicios Fiscales Anteriores Pendientes de Liquidación o Pago (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1054;
UPDATE C_Contable SET NombreCuenta='Transferencias del Sector Público (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1062;
UPDATE C_Contable SET NombreCuenta='Ayudas Sociales (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1064;
UPDATE C_Contable SET NombreCuenta='Transferencias del Exterior (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1646;
UPDATE C_Contable SET NombreCuenta='Otros Ingresos de Ejercicios Anteriores (Derogada)', Descripcion=' ', Utilizar=0 WHERE IdCuentaContable=1078;
-- 	END
-- ELSE
-- PRINT 'Para BD en uso: esta actualización debe aplicarse solamente a partir del 01-Enero-2019';

-- Cambios a cuentas contables no armonizadas en BD de Kórima, con estructura 5-5
UPDATE C_Contable SET NombreCuenta='Ingresos por Venta de Bienes y Prestación de Servicios' WHERE IdCuentaContable=1490;
UPDATE C_Contable SET NombreCuenta='Depreciación, deterioro y amortización acumulada de bienes e intangibles'  WHERE IdCuentaContable=129;
UPDATE C_Contable SET NombreCuenta='Patrimonio generado'  WHERE IdCuentaContable=184;
UPDATE C_Contable SET NombreCuenta='Inversión Pública'  WHERE IdCuentaContable=1176;